import { bulletinIds, flagIds } from './contentIds'
import type { Bulletin } from './types'

export const bulletins = [
  {
    id: bulletinIds.garbage,
    officialNumber: 1,
    category: '生活',
    official: true,
    visibilityCondition: { kind: 'day', comparison: 'gte', value: 1 },
    revisions: [
      {
        day: 1,
        status: 'posted',
        title: 'ごみ収集日の変更',
        body: '今週の燃やすごみは木曜日です。朝八時までに、各地区の集積所へお出しください。',
        changeNote: '白い紙に新しく掲示された。',
      },
      {
        day: 4,
        status: 'amended',
        title: 'ごみ収集日の変更（追記）',
        body: '木曜収集です。月影荘の集積所は水道工事のため、門の東側へ移ります。',
        changeNote: '東側、の四文字だけ青いインクで足された。',
      },
    ],
    variants: [],
  },
  {
    id: bulletinIds.streetlights,
    officialNumber: 2,
    category: '設備',
    official: true,
    visibilityCondition: { kind: 'day', comparison: 'gte', value: 1 },
    revisions: [
      {
        day: 1,
        status: 'posted',
        title: '商店街の街灯点検',
        body: '月影通りの街灯を、火曜の夕方に順番に点検します。短時間の消灯にご注意ください。',
        changeNote: '街灯の番号が一から十二まで手書きされている。',
      },
      {
        day: 3,
        status: 'amended',
        title: '商店街の街灯点検（完了）',
        body: '点検は完了しました。十二番灯の次にある無番号灯は、引き続き確認中です。',
        changeNote: '無番号灯の行が鉛筆で追記された。',
      },
    ],
    variants: [],
  },
  {
    id: bulletinIds.lostCat,
    officialNumber: 3,
    category: '捜しもの',
    official: true,
    visibilityCondition: { kind: 'day', comparison: 'gte', value: 1 },
    revisions: [
      {
        day: 1,
        status: 'posted',
        title: '迷い猫を見かけた方へ',
        body: '白と灰色の猫が町内を歩いています。飼い猫ではありません。無理に捕まえないでください。',
        changeNote: '猫の簡素な線画が添えられている。',
      },
      {
        day: 5,
        status: 'amended',
        title: '町猫ツキについて',
        body: '名前はツキです。首輪を外そうとせず、見かけた場所だけ管理人へお知らせください。',
        changeNote: '「迷い」の二文字に細い取り消し線が引かれた。',
      },
    ],
    variants: [],
  },
  {
    id: bulletinIds.river,
    officialNumber: 4,
    category: '町内会',
    official: true,
    visibilityCondition: { kind: 'day', comparison: 'gte', value: 1 },
    revisions: [
      {
        day: 1,
        status: 'posted',
        title: '河川清掃のお知らせ',
        body: '日曜朝七時、役場前集合です。雨天時は中止し、道具は町内会で用意します。',
        changeNote: '下端に十三年前の水染みが残る。',
      },
      {
        day: 6,
        status: 'removed',
        title: '河川清掃のお知らせ',
        body: '掲示は終了しました。画鋲と四角い日焼け跡だけが残っています。',
        changeNote: '紙が剥がされ、背後に古い「避難」の一字が見える。',
      },
    ],
    variants: [],
  },
  {
    id: bulletinIds.bookFair,
    officialNumber: 5,
    category: '催し',
    official: true,
    visibilityCondition: { kind: 'day', comparison: 'gte', value: 1 },
    revisions: [
      {
        day: 1,
        status: 'posted',
        title: '灯下書房・古書市',
        body: '今週末、店先で古書市を開きます。町史資料は閲覧のみ、持ち出しできません。',
        changeNote: '琥珀色の小さな紙片が挟まれている。',
      },
      {
        day: 2,
        status: 'amended',
        title: '灯下書房・古書市（貸出追記）',
        body: '町史資料の貸出は店主へご相談ください。返却時、挟まれた紙もお持ちください。',
        changeNote: '貸出不可の一文が、丁寧な字で改められた。',
      },
    ],
    variants: [],
  },
  {
    id: bulletinIds.cafeClosed,
    officialNumber: 6,
    category: '店舗',
    official: true,
    visibilityCondition: { kind: 'day', comparison: 'gte', value: 1 },
    revisions: [
      {
        day: 1,
        status: 'posted',
        title: '宵待の臨時休業',
        body: '水曜は機器点検のため、夜十時で閉店します。ラストオーダーは九時半です。',
        changeNote: 'ソーダ水色の紙に印刷されている。',
      },
      {
        day: 3,
        status: 'amended',
        title: '宵待の臨時休業（店内放送停止）',
        body: '点検中、店内ラジオを停止します。十一時十三分までは店員が残っています。',
        changeNote: '時刻だけ丸で囲まれ、色に頼らない注記が付いた。',
      },
    ],
    variants: [],
  },
  {
    id: bulletinIds.radioTest,
    officialNumber: 7,
    category: '防災',
    official: true,
    visibilityCondition: { kind: 'day', comparison: 'gte', value: 1 },
    revisions: [
      {
        day: 1,
        status: 'posted',
        title: '防災無線試験',
        body: '木曜正午、防災無線の試験音を流します。試験放送への応答は不要です。',
        changeNote: '公印の下に「十二回」と小さく書かれている。',
      },
      {
        day: 3,
        status: 'amended',
        title: '防災無線試験（夜間の音について）',
        body: '夜間に試験予定はありません。聞こえても返事をせず、翌朝役場へお知らせください。',
        changeNote: '紙の下端に、十三行目を切った跡がある。',
      },
    ],
    variants: [],
  },
  {
    id: bulletinIds.towerClosed,
    officialNumber: 8,
    category: '安全',
    official: true,
    visibilityCondition: { kind: 'day', comparison: 'gte', value: 1 },
    revisions: [
      {
        day: 1,
        status: 'posted',
        title: '放送塔周辺立入禁止',
        body: '斜面崩落のおそれがあります。許可なく柵の内側へ入らないでください。',
        changeNote: '榊巡査の署名と、立入禁止札の番号がある。',
      },
      {
        day: 6,
        status: 'amended',
        title: '放送塔への臨時立入について',
        body: '保守道の安全を確認しました。鍵を持つ同行者がいる場合に限り通行できます。',
        changeNote: '禁止の上へ、臨時許可の紙が重ねられた。',
      },
    ],
    variants: [],
  },
  {
    id: bulletinIds.water,
    officialNumber: 9,
    category: '設備',
    official: true,
    visibilityCondition: { kind: 'day', comparison: 'gte', value: 1 },
    revisions: [
      {
        day: 1,
        status: 'posted',
        title: '月影荘の水道点検',
        body: '金曜午後、各室の水道を点検します。在室できない方は管理人へ鍵をお預けください。',
        changeNote: '対象室は201、202、203。次の行だけ削られている。',
      },
      {
        day: 4,
        status: 'amended',
        title: '月影荘の水道点検（対象室訂正）',
        body: '対象は201、202、203号室です。旧204区画は203号室東側に含まれます。',
        changeNote: '旧204区画の一文が、管理人の白い紙で加わった。',
      },
    ],
    variants: [],
  },
  {
    id: bulletinIds.lostItem,
    officialNumber: 10,
    category: '捜しもの',
    official: true,
    visibilityCondition: { kind: 'day', comparison: 'gte', value: 1 },
    revisions: [
      {
        day: 1,
        status: 'posted',
        title: '落とし物のお知らせ',
        body: '真鍮の小さな名札を役場で預かっています。心当たりの方は住民課まで。',
        changeNote: '品名欄は「保守員証の留め具」。',
      },
      {
        day: 5,
        status: 'removed',
        title: '落とし物のお知らせ',
        body: '持ち主に関する記録が確認されました。掲示は役場で保管します。',
        changeNote: '紙は剥がされたが、四隅の画鋲だけ残った。',
      },
    ],
    variants: [],
  },
  {
    id: bulletinIds.festival,
    officialNumber: 11,
    category: '催し',
    official: true,
    visibilityCondition: { kind: 'day', comparison: 'gte', value: 1 },
    revisions: [
      {
        day: 1,
        status: 'posted',
        title: '夏祭り準備',
        body: '提灯の修繕を土曜午後に行います。作業台は役場裏、飲み物は宵待が用意します。',
        changeNote: '参加者欄は十二行で、最下段に薄い罫線がある。',
      },
      {
        day: 5,
        status: 'amended',
        title: '夏祭り準備（昔の名札募集）',
        body: '古い提灯の名札を探しています。読めない名前も消さず、そのままお持ちください。',
        changeNote: '「消さず」に二重の下線が引かれた。',
      },
    ],
    variants: [],
  },
  {
    id: bulletinIds.lastTrain,
    officialNumber: 12,
    category: '交通',
    official: true,
    visibilityCondition: { kind: 'day', comparison: 'gte', value: 1 },
    revisions: [
      {
        day: 1,
        status: 'posted',
        title: '最終列車時刻変更',
        body: '工事のため、月影町発の最終列車は二十二時四十分です。乗り遅れにご注意ください。',
        changeNote: '駅名欄の人数は、乗車十二名と記録されている。',
      },
      {
        day: 7,
        status: 'amended',
        title: '始発列車の運行',
        body: '始発は六時十分に発車します。乗車券は車内でもお求めいただけます。',
        changeNote: '最終、の紙を裏返し、始発、と書き直してある。',
      },
    ],
    variants: [],
  },
  {
    id: bulletinIds.thirteenth,
    officialNumber: 13,
    category: '差出人なし',
    official: false,
    visibilityCondition: {
      kind: 'all',
      conditions: [
        { kind: 'day', comparison: 'gte', value: 6 },
        { kind: 'clueCount', comparison: 'gte', value: 10 },
      ],
    },
    revisions: [
      {
        day: 6,
        status: 'posted',
        title: '十三番目のお知らせ',
        body: '忘れられた方へ。今夜、あなたの名前を返します。',
        changeNote: '十二枚の外側ではなく、紙跡だけだった隙間に収まっている。',
      },
    ],
    variants: [
      {
        id: 'public',
        condition: { kind: 'flag', flagId: flagIds.intentPublic, value: true },
        title: '十三番目――町の皆様へ',
        body: '{{playerName}}様へ。消した名前を、読める場所へ戻してください。',
      },
      {
        id: 'local',
        condition: { kind: 'flag', flagId: flagIds.intentLocal, value: true },
        title: '十三番目――覚えている方へ',
        body: '{{playerName}}様へ。小さな声でも、名前は町へ帰れます。',
      },
      {
        id: 'minato',
        condition: { kind: 'flag', flagId: flagIds.intentMinato, value: true },
        title: '十三番目――次に届ける方へ',
        body: '{{playerName}}様へ。返事ではなく、まだ届かない手紙をお願いします。',
      },
      {
        id: 'default',
        condition: { kind: 'always' },
        title: '十三番目のお知らせ',
        body: '忘れられた方へ。今夜、あなたの名前を返します。',
      },
    ],
  },
] as const satisfies readonly Bulletin[]

export const officialBulletins = bulletins.filter((bulletin) => bulletin.official)
export const thirteenthBulletin = bulletins.find((bulletin) => !bulletin.official)
