import {
  bulletinIds,
  chapterIds,
  clueIds,
  dialogueIds,
  flagIds,
  investigationIds,
  letterIds,
  locationIds,
  objectiveIds,
  sceneIds,
  subEventIds,
} from './contentIds'
import type { Chapter, HintStage } from './types'

const hints = (first: string, second: string, third: string): readonly HintStage[] => [
  { threshold: 0, text: first },
  { threshold: 1, text: second },
  { threshold: 2, text: third },
]

export const chapters = [
  {
    id: chapterIds.day0,
    day: 0,
    title: '転入',
    theme: '到着と所属の最初の手触り',
    opening: '封筒を開くと、終点のホームへ夕方の風が入り込んだ。最終列車が背後で扉を閉める。',
    objectives: [
      {
        id: objectiveIds.d0Arrive,
        title: '月影町へ降りる',
        description: '最終列車を降り、駅の時計と町への出口を確かめる。',
        required: true,
        completionCondition: { kind: 'locationVisited', locationId: locationIds.station },
        onComplete: [{ kind: 'completeObjective', objectiveId: objectiveIds.d0Arrive }],
        hints: hints(
          'ホームの終点標を見てみよう。',
          '駅時計は到着時だけ不自然な動きをする。',
          '時計を調べたら、青い庇の役場へ向かおう。',
        ),
      },
      {
        id: objectiveIds.d0Register,
        title: '転入届を出す',
        description: '役場で名前を書き、御影澄から住民票と203号室の鍵を受け取る。',
        required: true,
        completionCondition: { kind: 'flag', flagId: flagIds.registered, value: true },
        onComplete: [{ kind: 'completeObjective', objectiveId: objectiveIds.d0Register }],
        hints: hints(
          '駅を出て役場の住民課へ。',
          '人口表示も、名前を書く前後で見比べられる。',
          '澄との会話を終えると住民票と鍵を受け取れる。',
        ),
      },
      {
        id: objectiveIds.d0Mailbox,
        title: '月影荘の郵便受けを見る',
        description: '203号室へ入り、共同郵便受けに届いた宛先違いの封筒を確かめる。',
        required: true,
        completionCondition: { kind: 'flag', flagId: flagIds.mailboxOpened, value: true },
        onComplete: [{ kind: 'completeObjective', objectiveId: objectiveIds.d0Mailbox }],
        hints: hints(
          '鍵を受け取ったら、月影通りの先の月影荘へ。',
          '管理人こよみの話の後、玄関脇の共同郵便受けを調べよう。',
          '203の横幅が広い箱を開き、204号室宛の封筒を読む。',
        ),
      },
    ],
    scenes: [
      {
        id: sceneIds.d0Station,
        title: '終点の時計',
        locationId: locationIds.station,
        time: 'evening',
        summary: '最終列車が去り、駅時計が一瞬だけ11時13分を示す。',
        required: true,
        entryCondition: { kind: 'always' },
        completionCondition: { kind: 'locationVisited', locationId: locationIds.station },
        investigationIds: [investigationIds.stationClock],
        dialogueIds: [],
      },
      {
        id: sceneIds.d0TownHall,
        title: '青いインクの住民票',
        locationId: locationIds.townHall,
        time: 'evening',
        summary: '名前を書き、人口表示の揺れを見ながら月影町の住民になる。',
        required: true,
        entryCondition: { kind: 'locationVisited', locationId: locationIds.station },
        completionCondition: { kind: 'flag', flagId: flagIds.registered, value: true },
        investigationIds: [investigationIds.populationBoard],
        dialogueIds: [dialogueIds.sumiD0],
      },
      {
        id: sceneIds.d0Apartment,
        title: '203と204の間',
        locationId: locationIds.tsukikageHeights,
        time: 'night',
        summary: '管理人から部屋を案内され、星見湊宛の封筒を共同郵便受けで見つける。',
        required: true,
        entryCondition: { kind: 'flag', flagId: flagIds.roomKeyReceived, value: true },
        completionCondition: { kind: 'flag', flagId: flagIds.mailboxOpened, value: true },
        investigationIds: [investigationIds.mailbox204],
        dialogueIds: [dialogueIds.koyomiD0],
      },
    ],
    availableLetterIds: [letterIds.transferGuide, letterIds.to204],
    featuredBulletinIds: [],
    advanceCondition: {
      kind: 'all',
      conditions: [
        { kind: 'objectiveComplete', objectiveId: objectiveIds.d0Arrive },
        { kind: 'objectiveComplete', objectiveId: objectiveIds.d0Register },
        { kind: 'objectiveComplete', objectiveId: objectiveIds.d0Mailbox },
      ],
    },
    blockedMessage: '転入手続きと郵便受けの確認を終えると、203号室で最初の夜を迎えられます。',
    closing: '十二回のチャイムの後、短いノイズが窓の向こうで途切れた。返事を待つ声はまだない。',
  },
  {
    id: chapterIds.day1,
    day: 1,
    title: '町の挨拶',
    theme: '住民の日常へ混ざる',
    opening: '朝、郵便受けに差出人のない手紙がある。通りでは店の戸が順番に開いていく。',
    objectives: [
      {
        id: objectiveIds.d1Greet,
        title: '三人に挨拶する',
        description: '月影通り、灯下書房、宵待を歩き、町の住民三人以上と話す。',
        required: true,
        completionCondition: {
          kind: 'stat',
          statId: 'spokenCharacters',
          comparison: 'gte',
          value: 3,
        },
        onComplete: [{ kind: 'completeObjective', objectiveId: objectiveIds.d1Greet }],
        hints: hints(
          '月影通りには榊巡査がいる。二つの店も開いている。',
          '灯下書房の灯、宵待の奏、通りの榊と話してみよう。',
          '三人との初回会話を最後まで進める。選択に正解はない。',
        ),
      },
      {
        id: objectiveIds.d1VisitShop,
        title: '町の店へ入る',
        description: '灯下書房か宵待のどちらかを訪れ、町の暮らしに触れる。',
        required: true,
        completionCondition: {
          kind: 'any',
          conditions: [
            { kind: 'locationVisited', locationId: locationIds.toukaBooks },
            { kind: 'locationVisited', locationId: locationIds.yoimachiCafe },
          ],
        },
        onComplete: [{ kind: 'completeObjective', objectiveId: objectiveIds.d1VisitShop }],
        hints: hints(
          '橙色の看板は灯下書房、青緑の庇は宵待。',
          'どちらを先に訪ねても、物語上の不利益はない。',
          '店の入口へ近づき、調査操作で中へ入る。',
        ),
      },
      {
        id: objectiveIds.d1StartErrand,
        title: '小さな頼みを引き受ける',
        description: '破れた町史かツキの首輪など、サブイベントを一つ始める。',
        required: true,
        completionCondition: {
          kind: 'any',
          conditions: [
            { kind: 'subEvent', subEventId: subEventIds.tornHistory, state: 'started' },
            { kind: 'subEvent', subEventId: subEventIds.tsukiCollar, state: 'started' },
          ],
        },
        onComplete: [{ kind: 'completeObjective', objectiveId: objectiveIds.d1StartErrand }],
        hints: hints(
          '灯は町史の紙片を、通りのツキは首輪を気にしている。',
          '頼みを断定的な正解として扱う必要はない。まず話を聞こう。',
          '灯の町史を借りるか、ツキをそっと撫でると開始する。',
        ),
      },
    ],
    scenes: [
      {
        id: sceneIds.d1Street,
        title: '月影通りの住民',
        locationId: locationIds.mainStreet,
        time: 'evening',
        summary: '巡回中の榊と、路地に現れる猫ツキへ挨拶する。',
        required: true,
        entryCondition: { kind: 'always' },
        completionCondition: { kind: 'dialogueSeen', dialogueId: dialogueIds.renD1 },
        investigationIds: [],
        dialogueIds: [dialogueIds.renD1, dialogueIds.tsukiRepeat],
      },
      {
        id: sceneIds.d1Shop,
        title: '本とソーダの店',
        locationId: locationIds.mainStreet,
        time: 'evening',
        summary: '灯下書房と宵待で、町史と聞こえない放送の話を聞く。',
        required: true,
        entryCondition: { kind: 'always' },
        completionCondition: {
          kind: 'stat',
          statId: 'spokenCharacters',
          comparison: 'gte',
          value: 3,
        },
        investigationIds: [investigationIds.historyPage],
        dialogueIds: [dialogueIds.akariD1, dialogueIds.kanadeD1],
      },
    ],
    availableLetterIds: [letterIds.doNotDiscard],
    featuredBulletinIds: [
      bulletinIds.garbage,
      bulletinIds.streetlights,
      bulletinIds.lostCat,
      bulletinIds.river,
      bulletinIds.bookFair,
      bulletinIds.cafeClosed,
      bulletinIds.radioTest,
      bulletinIds.towerClosed,
      bulletinIds.water,
      bulletinIds.lostItem,
      bulletinIds.festival,
      bulletinIds.lastTrain,
    ],
    advanceCondition: {
      kind: 'all',
      conditions: [
        { kind: 'objectiveComplete', objectiveId: objectiveIds.d1Greet },
        { kind: 'objectiveComplete', objectiveId: objectiveIds.d1VisitShop },
        { kind: 'objectiveComplete', objectiveId: objectiveIds.d1StartErrand },
      ],
    },
    blockedMessage: '三人へ挨拶し、店を訪れ、小さな頼みを一つ引き受けると夜を進められます。',
    closing: '十二枚の掲示は風に鳴る。右下の空白だけ、紙がないのに画鋲の影を持っていた。',
  },
  {
    id: chapterIds.day2,
    day: 2,
    title: '消えた名前',
    theme: '記録に残る削除の形',
    opening: '青いインクは乾いている。それでも、削られた名前の溝には光が残っていた。',
    objectives: [
      {
        id: objectiveIds.d2Ledger,
        title: '古い台帳を調べる',
        description: '役場で星見湊の行と青い訂正、保守員証を確認する。',
        required: true,
        completionCondition: {
          kind: 'all',
          conditions: [
            { kind: 'clue', clueId: clueIds.blueInk },
            { kind: 'clue', clueId: clueIds.minatoBadge },
          ],
        },
        onComplete: [{ kind: 'completeObjective', objectiveId: objectiveIds.d2Ledger }],
        hints: hints(
          '役場の住民課で、古い背表紙の台帳を探す。',
          '人口表示の下ではなく、澄の机近くの資料箱にある。',
          '台帳と、間に挟まった保守員証の両方を調べる。',
        ),
      },
      {
        id: objectiveIds.d2History,
        title: '町史を借りる',
        description: '灯下書房で十三年前の巻を開き、切り取られた十三ページを確かめる。',
        required: true,
        completionCondition: { kind: 'clue', clueId: clueIds.missingPage13 },
        onComplete: [{ kind: 'completeObjective', objectiveId: objectiveIds.d2History }],
        hints: hints(
          '灯下書房の郷土資料棚へ。',
          '十三年前の巻だけ、棚の奥へ押し込まれている。',
          '十二ページの次が十四ページになっている箇所を調べる。',
        ),
      },
      {
        id: objectiveIds.d2Respond,
        title: '澄への向き合い方を選ぶ',
        description: '決めつけず尋ねる、証拠を確かめる、距離を取る、いずれかを選ぶ。',
        required: true,
        completionCondition: { kind: 'flag', flagId: flagIds.sumiAnswered, value: true },
        onComplete: [{ kind: 'completeObjective', objectiveId: objectiveIds.d2Respond }],
        hints: hints(
          '青い訂正跡を見つけた後、澄へ話しかける。',
          '選択は価値観の差で、どれでも進行できる。',
          '会話「消された行の前で」を最後まで進める。',
        ),
      },
    ],
    scenes: [
      {
        id: sceneIds.d2TownHall,
        title: '削られた台帳',
        locationId: locationIds.townHall,
        time: 'morning',
        summary: '湊の名が転出へ直された跡と、澄が抱えてきた沈黙に触れる。',
        required: true,
        entryCondition: { kind: 'always' },
        completionCondition: { kind: 'flag', flagId: flagIds.sumiAnswered, value: true },
        investigationIds: [
          investigationIds.ledger,
          investigationIds.badge,
          investigationIds.blueCorrection,
        ],
        dialogueIds: [dialogueIds.sumiD2],
      },
      {
        id: sceneIds.d2Books,
        title: '十三ページの切り口',
        locationId: locationIds.toukaBooks,
        time: 'evening',
        summary: '町史の欠落と、捨てられず各所へ分けられた紙片を調べる。',
        required: true,
        entryCondition: { kind: 'locationVisited', locationId: locationIds.toukaBooks },
        completionCondition: { kind: 'clue', clueId: clueIds.missingPage13 },
        investigationIds: [investigationIds.historyPage],
        dialogueIds: [dialogueIds.akariD2],
      },
    ],
    availableLetterIds: [letterIds.historyReturn],
    featuredBulletinIds: [bulletinIds.bookFair, bulletinIds.lostItem, bulletinIds.radioTest],
    advanceCondition: {
      kind: 'all',
      conditions: [
        { kind: 'objectiveComplete', objectiveId: objectiveIds.d2Ledger },
        { kind: 'objectiveComplete', objectiveId: objectiveIds.d2History },
        { kind: 'objectiveComplete', objectiveId: objectiveIds.d2Respond },
      ],
    },
    blockedMessage: '台帳と町史を調べ、青い訂正について澄へ返答すると次の日へ進めます。',
    closing: '切り取られたページの向こうで、雨の記録だけが十三年前から続いていた。',
  },
  {
    id: chapterIds.day3,
    day: 3,
    title: '聞こえない放送',
    theme: '聞くことと答えることの違い',
    opening: '宵待のカセットデッキへ、雨の夜が巻き戻される。ケースには題名がない。',
    objectives: [
      {
        id: objectiveIds.d3Cassette,
        title: '宵待でカセットを再生する',
        description: '奏と閉店後の喫茶へ残り、十二回のチャイムの先を聞く。',
        required: true,
        completionCondition: { kind: 'dialogueSeen', dialogueId: dialogueIds.kanadeD3 },
        onComplete: [{ kind: 'completeObjective', objectiveId: objectiveIds.d3Cassette }],
        hints: hints(
          '奏から届いた招待状を読み、夜の宵待へ。',
          'カウンター奥の古いデッキを奏と一緒に使う。',
          '会話「十二回の後」を最後まで進める。',
        ),
      },
      {
        id: objectiveIds.d3Broadcast,
        title: '放送への対応を選ぶ',
        description: '返事をする、黙って聞く、電源を切る、いずれかを自分の価値観で選ぶ。',
        required: true,
        completionCondition: {
          kind: 'any',
          conditions: [
            { kind: 'flag', flagId: flagIds.broadcastReplied, value: true },
            { kind: 'flag', flagId: flagIds.broadcastListened, value: true },
            { kind: 'flag', flagId: flagIds.broadcastCut, value: true },
          ],
        },
        onComplete: [{ kind: 'completeObjective', objectiveId: objectiveIds.d3Broadcast }],
        hints: hints(
          '放送が204号室を呼んだ時、三つの行動から選べる。',
          '電源を切っても進行不能にはならず、後日奏から補足を得られる。',
          '選択後、翌朝に榊へ行動を正直に伝える余地もある。',
        ),
      },
    ],
    scenes: [
      {
        id: sceneIds.d3Cafe,
        title: 'カセットのB面',
        locationId: locationIds.yoimachiCafe,
        time: 'night',
        summary: 'ケース裏のメモと、豪雨当日の避難先を読み上げる音声を確かめる。',
        required: true,
        entryCondition: { kind: 'day', comparison: 'gte', value: 3 },
        completionCondition: { kind: 'dialogueSeen', dialogueId: dialogueIds.kanadeD3 },
        investigationIds: [investigationIds.cassette],
        dialogueIds: [dialogueIds.kanadeD3, dialogueIds.minatoD3],
      },
      {
        id: sceneIds.d3Night,
        title: '11時13分の空白',
        locationId: locationIds.yoimachiCafe,
        time: 'night',
        summary: '204号室の転入届を預かっているという声へ、どう向き合うかを選ぶ。',
        required: true,
        entryCondition: { kind: 'dialogueSeen', dialogueId: dialogueIds.kanadeD3 },
        completionCondition: {
          kind: 'any',
          conditions: [
            { kind: 'flag', flagId: flagIds.broadcastReplied, value: true },
            { kind: 'flag', flagId: flagIds.broadcastListened, value: true },
            { kind: 'flag', flagId: flagIds.broadcastCut, value: true },
          ],
        },
        investigationIds: [],
        dialogueIds: [dialogueIds.renD3],
      },
    ],
    availableLetterIds: [letterIds.cafeInvitation],
    featuredBulletinIds: [bulletinIds.cafeClosed, bulletinIds.radioTest, bulletinIds.streetlights],
    advanceCondition: {
      kind: 'all',
      conditions: [
        { kind: 'objectiveComplete', objectiveId: objectiveIds.d3Cassette },
        { kind: 'objectiveComplete', objectiveId: objectiveIds.d3Broadcast },
      ],
    },
    blockedMessage: '夜の宵待でカセットを再生し、放送への対応を一つ選ぶと夜を終えられます。',
    closing: '選ばなかった行動の音も、カセットの空白へ薄く残った。店の時計は11時14分へ進む。',
  },
  {
    id: chapterIds.day4,
    day: 4,
    title: '204号室',
    theme: '怪異に包まれた生活上の事実',
    opening: '月影荘の廊下で、花模様が半分だけ合わない。こよみの鍵束は一枚ぶん軽い。',
    objectives: [
      {
        id: objectiveIds.d4Keys,
        title: '鍵束を整理する',
        description: 'こよみと鍵を部屋札へ戻し、204に部屋の鍵がないことを確かめる。',
        required: true,
        completionCondition: { kind: 'flag', flagId: flagIds.smallKeyFound, value: true },
        onComplete: [{ kind: 'completeObjective', objectiveId: objectiveIds.d4Keys }],
        hints: hints(
          '月影荘の管理人室で、こよみに話しかける。',
          '鍵の形より、部屋番号の刻印と鍵穴の擦れを見る。',
          '201・202・203を戻し、204の札と留め具の小鍵を調べる。',
        ),
      },
      {
        id: objectiveIds.d4Door,
        title: '壁紙の下の扉を確かめる',
        description: '203号室東側の廊下で、模様のずれと旧扉の輪郭を調べる。',
        required: true,
        completionCondition: { kind: 'flag', flagId: flagIds.doorOutlineFound, value: true },
        onComplete: [{ kind: 'completeObjective', objectiveId: objectiveIds.d4Door }],
        hints: hints(
          '203号室の扉から東へ、花模様をたどる。',
          '壁紙の模様が半分ずれた場所で調査する。',
          '扉跡の蝶番と「二室統合」の鉛筆書きを確認する。',
        ),
      },
      {
        id: objectiveIds.d4Mailbox,
        title: '郵便受けの二重底を開ける',
        description: '小鍵を203の共同郵便受けへ使い、湊の未送信手紙を読む。',
        required: true,
        completionCondition: { kind: 'flag', flagId: flagIds.doubleBottomOpened, value: true },
        onComplete: [{ kind: 'completeObjective', objectiveId: objectiveIds.d4Mailbox }],
        hints: hints(
          '鍵束の留め具から見つけた小鍵は、部屋用ではない。',
          '共同郵便受け203の底を叩き、乾いた音の場所を見る。',
          '小鍵で底板を開き、未送信の転出届と手紙を記録する。',
        ),
      },
    ],
    scenes: [
      {
        id: sceneIds.d4Hallway,
        title: '統合された二室',
        locationId: locationIds.tsukikageHeights,
        time: 'evening',
        summary: '鍵、壁紙、間取りから、旧204が203へ統合された改装の事実へ届く。',
        required: true,
        entryCondition: { kind: 'day', comparison: 'gte', value: 4 },
        completionCondition: { kind: 'flag', flagId: flagIds.doorOutlineFound, value: true },
        investigationIds: [investigationIds.doorOutline, investigationIds.floorplan],
        dialogueIds: [dialogueIds.koyomiD4],
      },
      {
        id: sceneIds.d4Mailbox,
        title: '二重底の手紙',
        locationId: locationIds.tsukikageHeights,
        time: 'night',
        summary: '郵便物を消すのでなく守ってきた二重底と、湊本人の未送信手紙を見つける。',
        required: true,
        entryCondition: { kind: 'flag', flagId: flagIds.smallKeyFound, value: true },
        completionCondition: { kind: 'flag', flagId: flagIds.doubleBottomOpened, value: true },
        investigationIds: [investigationIds.mailboxBottom],
        dialogueIds: [dialogueIds.minatoD4],
      },
    ],
    availableLetterIds: [letterIds.minatoUnsent],
    featuredBulletinIds: [bulletinIds.water, bulletinIds.lostCat],
    advanceCondition: {
      kind: 'all',
      conditions: [
        { kind: 'objectiveComplete', objectiveId: objectiveIds.d4Keys },
        { kind: 'objectiveComplete', objectiveId: objectiveIds.d4Door },
        { kind: 'objectiveComplete', objectiveId: objectiveIds.d4Mailbox },
      ],
    },
    blockedMessage: '鍵束、廊下の扉跡、郵便受けの二重底を順に確かめると一日を終えられます。',
    closing: '204号室は消えていなかった。203号室の壁と郵便受けの中で、説明を待っていた。',
  },
  {
    id: chapterIds.day5,
    day: 5,
    title: 'それぞれの記憶',
    theme: '誰か一人を悪役にしない証言',
    opening: '同じ豪雨を、五人は別の窓から覚えていた。どの話にも、守ったものと伏せたものがある。',
    objectives: [
      {
        id: objectiveIds.d5Testimony,
        title: '三人以上から証言を聞く',
        description: '澄、灯、奏、榊、こよみのうち三人以上から、異なる記憶を聞く。',
        required: true,
        completionCondition: {
          kind: 'stat',
          statId: 'testimoniesHeard',
          comparison: 'gte',
          value: 3,
        },
        onComplete: [{ kind: 'completeObjective', objectiveId: objectiveIds.d5Testimony }],
        hints: hints(
          '役場、灯下書房、宵待、通り、月影荘を巡る。',
          '信頼が高い相手は、個人的な記録まで見せてくれる。',
          '五人のうち任意の三人のDay 5会話を最後まで進める。',
        ),
      },
      {
        id: objectiveIds.d5Intent,
        title: '記録の行き先を考える',
        description: '公開、町の中の記憶、湊の望みの探索から、現在の考えを一つ伝える。',
        required: true,
        completionCondition: {
          kind: 'any',
          conditions: [
            { kind: 'flag', flagId: flagIds.intentPublic, value: true },
            { kind: 'flag', flagId: flagIds.intentLocal, value: true },
            { kind: 'flag', flagId: flagIds.intentMinato, value: true },
          ],
        },
        onComplete: [{ kind: 'completeObjective', objectiveId: objectiveIds.d5Intent }],
        hints: hints(
          '澄は集めた記録をどうしたいか尋ねる。',
          'ここでの考えは最終選択を固定せず、十三番目の文面を変える。',
          '澄のDay 5会話で三つの方針から一つを選ぶ。',
        ),
      },
    ],
    scenes: [
      {
        id: sceneIds.d5Testimony,
        title: '五つの窓から見た豪雨',
        locationId: locationIds.mainStreet,
        time: 'evening',
        summary: '資料を守ったこと、沈黙したこと、命令に従ったことを、結果と動機の両方から聞く。',
        required: true,
        entryCondition: { kind: 'day', comparison: 'gte', value: 5 },
        completionCondition: {
          kind: 'stat',
          statId: 'testimoniesHeard',
          comparison: 'gte',
          value: 3,
        },
        investigationIds: [investigationIds.familyPhoto, investigationIds.renLog],
        dialogueIds: [
          dialogueIds.sumiD5Low,
          dialogueIds.sumiD5High,
          dialogueIds.akariD5Low,
          dialogueIds.akariD5High,
          dialogueIds.kanadeD5Low,
          dialogueIds.kanadeD5High,
          dialogueIds.renD5Low,
          dialogueIds.renD5High,
          dialogueIds.koyomiD5Low,
          dialogueIds.koyomiD5High,
        ],
      },
    ],
    availableLetterIds: [letterIds.sumiMeeting, letterIds.renSafetyNote],
    featuredBulletinIds: [bulletinIds.festival, bulletinIds.lostCat, bulletinIds.lostItem],
    advanceCondition: {
      kind: 'all',
      conditions: [
        { kind: 'objectiveComplete', objectiveId: objectiveIds.d5Testimony },
        { kind: 'objectiveComplete', objectiveId: objectiveIds.d5Intent },
      ],
    },
    blockedMessage: '五人のうち三人から証言を聞き、記録の行き先について今の考えを伝えてください。',
    closing: '違う証言は互いを消さず、同じ夜の輪郭を少しずつ濃くした。',
  },
  {
    id: chapterIds.day6,
    day: 6,
    title: '十三番目の回覧板',
    theme: '空白へ現れる個人的なお知らせ',
    opening: '掲示板の右下に、昨日まで紙跡だけだった場所へ一枚が増えている。',
    objectives: [
      {
        id: objectiveIds.d6Notice,
        title: '十三番目を読む',
        description: '十二枚の外に現れた紙を調べ、放送塔への道順を日記へ記録する。',
        required: true,
        completionCondition: { kind: 'clue', clueId: clueIds.thirteenthNotice },
        onComplete: [
          { kind: 'completeObjective', objectiveId: objectiveIds.d6Notice },
          { kind: 'unlockLocation', locationId: locationIds.broadcastHill },
        ],
        hints: hints(
          '町内掲示板の右下、古い紙跡を見る。',
          '手掛かりを十個集めると、十三枚目が隙間へ現れる。',
          '十三番目を開いてから、裏面と画鋲穴も調べる。',
        ),
      },
      {
        id: objectiveIds.d6Companion,
        title: '丘へ行く方法を決める',
        description: '榊へ同行を頼むか、安全な保守道を一人で進むか選ぶ。',
        required: true,
        completionCondition: {
          kind: 'any',
          conditions: [
            { kind: 'flag', flagId: flagIds.companionAsked, value: true },
            { kind: 'flag', flagId: flagIds.companionAlone, value: true },
          ],
        },
        onComplete: [{ kind: 'completeObjective', objectiveId: objectiveIds.d6Companion }],
        hints: hints(
          '十三番目を読んだ後、掲示板を見回る榊へ話しかける。',
          '同行の有無は結末の優劣を決めない。安全な経路だけが変わる。',
          '会話「丘へ向かう前に」で二つの方法から選ぶ。',
        ),
      },
    ],
    scenes: [
      {
        id: sceneIds.d6Board,
        title: '十二枚の外側',
        locationId: locationIds.bulletinBoard,
        time: 'evening',
        summary: 'プレイヤーの方針を映した十三番目と、十三年前から重なる画鋲穴を読む。',
        required: true,
        entryCondition: { kind: 'clueCount', comparison: 'gte', value: 10 },
        completionCondition: { kind: 'clue', clueId: clueIds.thirteenthNotice },
        investigationIds: [investigationIds.noticeGap],
        dialogueIds: [dialogueIds.renD6Companion],
      },
      {
        id: sceneIds.d6HillRoad,
        title: '塔へ続く二つの道',
        locationId: locationIds.broadcastHill,
        time: 'night',
        summary: '榊の許可札かツキの古道を選び、翌夜に備えて塔の入口を確かめる。',
        required: false,
        entryCondition: { kind: 'clue', clueId: clueIds.thirteenthNotice },
        completionCondition: { kind: 'locationVisited', locationId: locationIds.broadcastHill },
        investigationIds: [investigationIds.towerFence],
        dialogueIds: [dialogueIds.tsukiRepeat],
      },
    ],
    availableLetterIds: [],
    featuredBulletinIds: [bulletinIds.thirteenth, bulletinIds.towerClosed],
    advanceCondition: {
      kind: 'all',
      conditions: [
        { kind: 'objectiveComplete', objectiveId: objectiveIds.d6Notice },
        { kind: 'objectiveComplete', objectiveId: objectiveIds.d6Companion },
      ],
    },
    blockedMessage: '十三番目の裏面を調べ、榊と丘へ行く方法を決めると最終日へ進めます。',
    closing: '放送塔の赤色灯が十三秒ごとにまたたく。町の窓は、まだ普段どおり明るい。',
  },
  {
    id: chapterIds.day7,
    day: 7,
    title: '放送塔',
    theme: '名前の行き先を選ぶ',
    opening: '丘の上では、町の灯りが台帳の行のように並ぶ。古いマイクだけが空欄を向いている。',
    objectives: [
      {
        id: objectiveIds.d7Recording,
        title: '湊の最後の録音を聞く',
        description: '放送卓と台帳端末の配線を確かめ、豪雨当日の最後の音声を再生する。',
        required: true,
        completionCondition: { kind: 'flag', flagId: flagIds.finalRecordingHeard, value: true },
        onComplete: [{ kind: 'completeObjective', objectiveId: objectiveIds.d7Recording }],
        hints: hints(
          '放送塔の操作室で、十三番の手書きボタンを探す。',
          '先に配線図を見ると、台帳端末との接続を理解しやすい。',
          '放送卓を調べ、湊の最後の録音を最後まで聞く。',
        ),
      },
      {
        id: objectiveIds.d7Decision,
        title: '名前の行き先を選ぶ',
        description: '町へ返す、外へ持ち出す、役目を引き継ぐ、三つから最終選択を行う。',
        required: true,
        completionCondition: { kind: 'flag', flagId: flagIds.finalDecisionMade, value: true },
        onComplete: [{ kind: 'completeObjective', objectiveId: objectiveIds.d7Decision }],
        hints: hints(
          '録音後、放送卓に三つの操作が現れる。',
          'どの選択にも守れるものと代償があり、物語上の正解は一つではない。',
          '町へ名前を返す／記録を外へ／十三番目を継ぐ、から選ぶ。',
        ),
      },
    ],
    scenes: [
      {
        id: sceneIds.d7Tower,
        title: '台帳につながる放送卓',
        locationId: locationIds.broadcastHill,
        time: 'night',
        summary: '消された名前が十三番へ蓄積し、現在の住民まで巻き込み始めた仕組みを知る。',
        required: true,
        entryCondition: { kind: 'day', comparison: 'eq', value: 7 },
        completionCondition: { kind: 'flag', flagId: flagIds.finalRecordingHeard, value: true },
        investigationIds: [investigationIds.towerConsole],
        dialogueIds: [dialogueIds.minatoD7Sparse, dialogueIds.minatoD7Full],
      },
      {
        id: sceneIds.d7Decision,
        title: '十三番目の行き先',
        locationId: locationIds.broadcastHill,
        time: 'night',
        summary: '湊の善意と放置された危険を受け止め、名前と記録をどこへ渡すか選ぶ。',
        required: true,
        entryCondition: { kind: 'flag', flagId: flagIds.finalRecordingHeard, value: true },
        completionCondition: { kind: 'flag', flagId: flagIds.finalDecisionMade, value: true },
        investigationIds: [],
        dialogueIds: [dialogueIds.minatoD7Sparse, dialogueIds.minatoD7Full],
      },
    ],
    availableLetterIds: [
      letterIds.endingA,
      letterIds.endingB,
      letterIds.endingC,
      letterIds.endingD,
    ],
    featuredBulletinIds: [bulletinIds.thirteenth, bulletinIds.lastTrain],
    advanceCondition: {
      kind: 'all',
      conditions: [
        { kind: 'objectiveComplete', objectiveId: objectiveIds.d7Recording },
        { kind: 'objectiveComplete', objectiveId: objectiveIds.d7Decision },
      ],
    },
    blockedMessage: '最後の録音を聞き、放送卓で名前の行き先を選ぶと結末へ進みます。',
    closing: 'マイクの灯りが消えても、町の生活音は続く。選んだ行き先へ、最初の手紙が届く。',
  },
] as const satisfies readonly Chapter[]
