import { characterIds, locationIds } from './contentIds'
import type { CharacterProfile } from './types'

export const characters = [
  {
    id: characterIds.sumi,
    name: '御影 澄',
    reading: 'みかげ すみ',
    ageLabel: '29歳',
    kind: 'person',
    namedCharacter: true,
    role: '町役場・住民課職員',
    publicBio: '静かな声で手続きを進める職員。書類の数字より、書いた人の顔をよく見る。',
    privateTruth: '星見湊の妹。兄を転出扱いにした記録を知り、町を守るため沈黙してきた。',
    voiceGuide: '短く丁寧。迷うときは言い直さず、青いペンを一度置く。',
    symbols: ['青いインク', '役場の鍵', '家族写真'],
    homeLocationId: locationIds.townHall,
    trustTrack: true,
    trustGuide: '結論を迫らず、彼女の立場と守りたかった人を尋ねると信頼が上がる。',
    schedule: [
      { days: 'all', time: 'morning', locationId: locationIds.townHall, note: '住民課の窓口' },
      {
        days: [0, 2, 5],
        time: 'evening',
        locationId: locationIds.townHall,
        note: '古い書類を整理',
      },
      { days: [5, 6], time: 'night', locationId: locationIds.mainStreet, note: '役場からの帰り道' },
    ],
  },
  {
    id: characterIds.akari,
    name: '久世 灯',
    reading: 'くぜ あかり',
    ageLabel: '67歳',
    kind: 'person',
    namedCharacter: true,
    role: '古書店「灯下書房」店主',
    publicBio: '町史と古地図を守る店主。答えではなく、読むべき棚を教えてくれる。',
    privateTruth: '豪雨後に捨てられかけた回覧板を拾い、切られた町史の紙片を分けて隠した。',
    voiceGuide: '比喩は使うが煙に巻かない。大事な語の前で、本の埃を払う。',
    symbols: ['古書', '琥珀色のランプ', '破れた町史'],
    homeLocationId: locationIds.toukaBooks,
    trustTrack: true,
    trustGuide: '資料を丁寧に扱い、分からないことを分からないまま聞くと信頼が上がる。',
    schedule: [
      { days: 'all', time: 'morning', locationId: locationIds.toukaBooks, note: '開店準備' },
      { days: 'all', time: 'evening', locationId: locationIds.toukaBooks, note: '店番' },
      { days: [2, 5], time: 'night', locationId: locationIds.toukaBooks, note: '町史の修復' },
    ],
  },
  {
    id: characterIds.kanade,
    name: '雨宮 奏',
    reading: 'あまみや かなで',
    ageLabel: '24歳',
    kind: 'person',
    namedCharacter: true,
    role: '喫茶「宵待」店員',
    publicBio: '話しかけやすく町の噂に詳しい。飲み物の名を少し大げさに紹介する。',
    privateTruth: '幼い夜に十三番目の放送を聞き、自分が返事をしたのか今も確信がない。',
    voiceGuide: '明るく柔らかい。怖い話ほど日常の音に置き換えて話す。',
    symbols: ['クリームソーダ', '古いカセット', '雨音'],
    homeLocationId: locationIds.yoimachiCafe,
    trustTrack: true,
    trustGuide: '噂と切り捨てず、怖かった記憶を笑わずに受け止めると信頼が上がる。',
    schedule: [
      { days: 'all', time: 'evening', locationId: locationIds.yoimachiCafe, note: 'カウンター' },
      { days: [3, 5], time: 'night', locationId: locationIds.yoimachiCafe, note: '閉店後の片付け' },
      { days: [1, 6], time: 'morning', locationId: locationIds.mainStreet, note: '買い出し' },
    ],
  },
  {
    id: characterIds.ren,
    name: '榊 蓮',
    reading: 'さかき れん',
    ageLabel: '35歳',
    kind: 'person',
    namedCharacter: true,
    role: '月影町駐在所・巡査',
    publicBio: '現実的で規則を重んじる巡査。夜道では誰より先に懐中電灯を向ける。',
    privateTruth: '父が豪雨事故後の記録改変に関わった。怪異より、再び誰かが傷つく混乱を恐れる。',
    voiceGuide: '断定は証拠がある時だけ。忠告の最後に、帰路を具体的に教える。',
    symbols: ['懐中電灯', '立入禁止札', '父の業務日誌'],
    homeLocationId: locationIds.mainStreet,
    trustTrack: true,
    trustGuide: '無断侵入を避け、出所の分かる証拠を見せると信頼が上がる。',
    schedule: [
      { days: 'all', time: 'morning', locationId: locationIds.mainStreet, note: '町内巡回' },
      { days: [1, 3, 5], time: 'evening', locationId: locationIds.bulletinBoard, note: '掲示確認' },
      { days: [3, 6, 7], time: 'night', locationId: locationIds.mainStreet, note: '夜間巡回' },
    ],
  },
  {
    id: characterIds.koyomi,
    name: '月白 こよみ',
    reading: 'つきしろ こよみ',
    ageLabel: '年齢非公開',
    kind: 'person',
    namedCharacter: true,
    role: '月影荘管理人',
    publicBio: '白い鍵束を持つ管理人。昔から変わらない、という町の噂を否定もしない。',
    privateTruth: '母娘が同じ名と装いを引き継いできた。204号室の郵便物を代々保管している。',
    voiceGuide: '冗談めいた言葉で入口を作り、問われれば生活の事実をきちんと答える。',
    symbols: ['白い鍵', '月形の髪留め', '共同郵便受け'],
    homeLocationId: locationIds.tsukikageHeights,
    trustTrack: true,
    trustGuide: '怪異扱いで決めつけず、建物と郵便物を守った仕事へ目を向けると信頼が上がる。',
    schedule: [
      {
        days: 'all',
        time: 'morning',
        locationId: locationIds.tsukikageHeights,
        note: '玄関の掃除',
      },
      { days: 'all', time: 'evening', locationId: locationIds.tsukikageHeights, note: '管理人室' },
      {
        days: [0, 4, 5],
        time: 'night',
        locationId: locationIds.tsukikageHeights,
        note: '郵便受けの確認',
      },
    ],
  },
  {
    id: characterIds.minato,
    name: '星見 湊',
    reading: 'ほしみ みなと',
    ageLabel: '失踪時31歳',
    kind: 'echo',
    namedCharacter: true,
    role: '元・放送塔保守員',
    publicBio: '十三年前に行方不明となった保守員。手紙、録音、放送の声として残る。',
    privateTruth: '避難放送で住民を救い、自分の不在後も忘れられた名前を届ける仕組みを残した。',
    voiceGuide: '命令しない。聞き手に返事を求めず、覚えてほしい事実だけを置く。',
    symbols: ['十三番目の紙片', '古いマイク', '保守員証'],
    homeLocationId: locationIds.room203,
    trustTrack: false,
    trustGuide: '信頼値は持たない。複数の記録を重ねるほど、録音の欠けた部分が補われる。',
    schedule: [
      { days: [3], time: 'night', locationId: locationIds.yoimachiCafe, note: 'カセットの声' },
      { days: [4], time: 'night', locationId: locationIds.room203, note: '未送信手紙の朗読' },
      { days: [7], time: 'night', locationId: locationIds.broadcastHill, note: '最後の録音' },
    ],
  },
  {
    id: characterIds.tsuki,
    name: 'ツキ',
    reading: 'つき',
    ageLabel: '猫',
    kind: 'cat',
    namedCharacter: false,
    role: '町を歩く白と灰色の猫',
    publicBio: '重要な場所の少し手前で尻尾を揺らす。撫でても謎の答えは教えない。',
    privateTruth: '湊が保護していた猫の子孫。首輪の「H.M.」と放送塔への古道を受け継ぐ。',
    voiceGuide: '鳴き声と仕草だけ。人間の言葉や説明役にはしない。',
    symbols: ['H.M.の首輪', '灰色の尾', '古い保守道'],
    homeLocationId: locationIds.mainStreet,
    trustTrack: false,
    trustGuide: '撫でた回数を記録する。信頼会話の代わりに行動で親しさを示す。',
    schedule: [
      { days: [1, 2], time: 'evening', locationId: locationIds.mainStreet, note: '路地の入口' },
      {
        days: [3, 4],
        time: 'night',
        locationId: locationIds.tsukikageHeights,
        note: '郵便受けのそば',
      },
      {
        days: [5, 6, 7],
        time: 'evening',
        locationId: locationIds.broadcastHill,
        note: '古道の手前',
      },
    ],
  },
] as const satisfies readonly CharacterProfile[]
