import {
  bulletinIds,
  clueIds,
  dialogueIds,
  investigationIds,
  letterIds,
  locationIds,
  subEventIds,
} from './contentIds'
import type { Clue } from './types'

export const clues = [
  {
    id: clueIds.envelope204,
    title: '204号室宛の封筒',
    shortFact: '存在しないはずの204号室、星見湊宛の古い封筒が203の郵便受けへ届いた。',
    interpretation: '郵便の経路は、部屋番号が消えた後も204と203を同じ場所として扱っている。',
    dayAvailable: 0,
    locationIds: [locationIds.tsukikageHeights, locationIds.room203],
    sourceRefs: [
      { kind: 'letter', letterId: letterIds.to204 },
      { kind: 'investigation', investigationId: investigationIds.mailbox204 },
    ],
    tags: ['room-204', 'record'],
  },
  {
    id: clueIds.populationFlicker,
    title: '人口表示の揺れ',
    shortFact: '役場の表示が、転入手続きの前後で1,284人と1,285人の間を揺れた。',
    interpretation: '掲示人口と住民台帳は同じ数え方をしていない。新しい住民だけの問題でもない。',
    dayAvailable: 0,
    locationIds: [locationIds.townHall],
    sourceRefs: [
      { kind: 'investigation', investigationId: investigationIds.populationBoard },
      { kind: 'dialogue', dialogueId: dialogueIds.sumiD0 },
    ],
    tags: ['record'],
  },
  {
    id: clueIds.missingPage13,
    title: '切り取られた町史13ページ',
    shortFact: '豪雨を記した巻の十三ページが、根元から三枚に分けて切り取られている。',
    interpretation: '事故そのものより、最後の放送について書かれた箇所を後から隠した形跡がある。',
    dayAvailable: 2,
    locationIds: [locationIds.toukaBooks, locationIds.station, locationIds.bulletinBoard],
    sourceRefs: [
      { kind: 'investigation', investigationId: investigationIds.historyPage },
      { kind: 'subEvent', subEventId: subEventIds.tornHistory },
    ],
    tags: ['record', 'disaster', 'broadcast'],
  },
  {
    id: clueIds.minatoBadge,
    title: '星見湊の保守員証',
    shortFact: '星見湊が放送設備保守員だったことを示す真鍮の身分証。写真だけ剥がれている。',
    interpretation: '湊は放送へ偶然巻き込まれたのでなく、設備と記録の接続を知る立場にいた。',
    dayAvailable: 2,
    locationIds: [locationIds.townHall, locationIds.toukaBooks],
    sourceRefs: [
      { kind: 'investigation', investigationId: investigationIds.badge },
      { kind: 'dialogue', dialogueId: dialogueIds.akariD2 },
    ],
    tags: ['record', 'broadcast'],
  },
  {
    id: clueIds.clock1113,
    title: '11時13分で止まった時計',
    shortFact: '駅時計は列車が去った一瞬だけ午後11時13分を示し、すぐ正しい時刻へ戻った。',
    interpretation: '十三年前の放送時刻が、現在の設備や町の記憶へ残っている。',
    dayAvailable: 0,
    locationIds: [locationIds.station],
    sourceRefs: [
      { kind: 'investigation', investigationId: investigationIds.stationClock },
      { kind: 'dialogue', dialogueId: dialogueIds.koyomiD0 },
    ],
    tags: ['broadcast', 'disaster'],
  },
  {
    id: clueIds.blueInk,
    title: '青いインクの訂正跡',
    shortFact: '星見湊の台帳行は削られ、転出と青字で重ねられた。転出先は空欄のまま。',
    interpretation: '澄の筆跡ではない。豪雨後の命令で、行方不明を転出へ置き換えた記録だ。',
    dayAvailable: 2,
    locationIds: [locationIds.townHall],
    sourceRefs: [
      { kind: 'investigation', investigationId: investigationIds.blueCorrection },
      { kind: 'dialogue', dialogueId: dialogueIds.sumiD2 },
    ],
    tags: ['record', 'family', 'disaster'],
  },
  {
    id: clueIds.mailboxFalseBottom,
    title: '二重底の郵便受け',
    shortFact: '203の共同郵便受けには小鍵で開く二重底があり、湊の手紙を湿気から守っていた。',
    interpretation:
      '204宛の郵便物を隠して消す仕掛けでなく、宛先が戻るまで保管するための場所だった。',
    dayAvailable: 4,
    locationIds: [locationIds.tsukikageHeights],
    sourceRefs: [
      { kind: 'investigation', investigationId: investigationIds.mailboxBottom },
      { kind: 'letter', letterId: letterIds.minatoUnsent },
    ],
    tags: ['room-204', 'record'],
  },
  {
    id: clueIds.evacuationLog,
    title: '豪雨当日の避難放送記録',
    shortFact: '湊は孤立した家を一軒ずつ呼び、避難完了を確認してから自分も保守道へ向かった。',
    interpretation:
      '十三番目は混乱を招いた怪異ではなく、届かない相手へ最後の情報を渡す私信だった。',
    dayAvailable: 3,
    locationIds: [locationIds.yoimachiCafe, locationIds.broadcastHill],
    sourceRefs: [
      { kind: 'subEvent', subEventId: subEventIds.cafeCassette },
      { kind: 'dialogue', dialogueId: dialogueIds.minatoD7Full },
    ],
    tags: ['broadcast', 'disaster'],
  },
  {
    id: clueIds.sumiPhoto,
    title: '澄の家族写真',
    shortFact: '放送塔前で幼い澄と湊が並ぶ写真。裏には「兄さん、帰ったら」の書きかけがある。',
    interpretation: '町の記録が消えても、澄は兄を忘れていない。沈黙は同意だけではなかった。',
    dayAvailable: 5,
    locationIds: [locationIds.townHall],
    sourceRefs: [
      { kind: 'investigation', investigationId: investigationIds.familyPhoto },
      { kind: 'dialogue', dialogueId: dialogueIds.sumiD5High },
    ],
    tags: ['family', 'record'],
  },
  {
    id: clueIds.renFatherLog,
    title: '榊の父の業務日誌',
    shortFact: '豪雨後、混乱を避けるため湊を転出処理した命令と、従った巡査の後悔が残る。',
    interpretation: '記録改変は単純な悪意でなく、責任回避と住民保護が混ざった判断だった。',
    dayAvailable: 5,
    locationIds: [locationIds.mainStreet],
    sourceRefs: [
      { kind: 'investigation', investigationId: investigationIds.renLog },
      { kind: 'letter', letterId: letterIds.renSafetyNote },
    ],
    tags: ['record', 'disaster'],
  },
  {
    id: clueIds.cassetteBack,
    title: 'カセット裏面のメモ',
    shortFact: 'ケース裏に「十二の後、返事不要」とH.M.の頭文字が青い字で記されている。',
    interpretation: '夜の放送は応答を集めるためでなく、聞き手へ記憶を預けるために作られた。',
    dayAvailable: 3,
    locationIds: [locationIds.yoimachiCafe],
    sourceRefs: [
      { kind: 'investigation', investigationId: investigationIds.cassette },
      { kind: 'subEvent', subEventId: subEventIds.cafeCassette },
    ],
    tags: ['broadcast'],
  },
  {
    id: clueIds.oldFloorplan,
    title: '古い月影荘の間取り',
    shortFact: '旧203と204は配管工事で一室へ統合され、改装後は203号室と記録されている。',
    interpretation:
      '204は怪異で消えたのではない。町が説明を避けたため、生活上の事実が噂へ変わった。',
    dayAvailable: 4,
    locationIds: [locationIds.tsukikageHeights, locationIds.room203],
    sourceRefs: [
      { kind: 'investigation', investigationId: investigationIds.floorplan },
      { kind: 'dialogue', dialogueId: dialogueIds.koyomiD4 },
    ],
    tags: ['room-204', 'record'],
  },
  {
    id: clueIds.thirteenthNotice,
    title: '十三番目の回覧板',
    shortFact: '十二枚の外の古い紙跡へ、「忘れられた方へ」と書かれた一枚が現れた。',
    interpretation: '十三番目は町を脅す告知でなく、消された名前を返すため放送塔へ導く私信だ。',
    dayAvailable: 6,
    locationIds: [locationIds.bulletinBoard],
    sourceRefs: [
      { kind: 'bulletin', bulletinId: bulletinIds.thirteenth },
      { kind: 'investigation', investigationId: investigationIds.noticeGap },
    ],
    tags: ['broadcast', 'record'],
  },
  {
    id: clueIds.towerKey,
    title: '放送塔の鍵',
    shortFact: 'H.M.と刻まれた小門の鍵。ツキの首輪と同じ頭文字があり、古い保守道を開ける。',
    interpretation: '湊が使った経路は残っている。正面の柵を破らなくても、塔へ安全に近づける。',
    dayAvailable: 6,
    locationIds: [locationIds.broadcastHill],
    sourceRefs: [
      { kind: 'investigation', investigationId: investigationIds.towerFence },
      { kind: 'subEvent', subEventId: subEventIds.tsukiCollar },
    ],
    tags: ['broadcast', 'disaster'],
  },
  {
    id: clueIds.unsentMoveOut,
    title: '未送信の転出届',
    shortFact: '湊の署名はあるが、転出先と日付は空欄。「不在と不実在は違う」と添えられている。',
    interpretation: '町が後に作った転出記録は本人の意思ではない。湊は町へ名前を残そうとしていた。',
    dayAvailable: 4,
    locationIds: [locationIds.tsukikageHeights, locationIds.room203],
    sourceRefs: [
      { kind: 'letter', letterId: letterIds.minatoUnsent },
      { kind: 'dialogue', dialogueId: dialogueIds.minatoD4 },
    ],
    tags: ['record', 'room-204', 'family'],
  },
] as const satisfies readonly Clue[]
