import { ids } from './types'

export const locationIds = {
  station: ids.location('station'),
  townHall: ids.location('town_hall'),
  mainStreet: ids.location('main_street'),
  bulletinBoard: ids.location('bulletin_board'),
  toukaBooks: ids.location('touka_books'),
  yoimachiCafe: ids.location('yoi_machi'),
  tsukikageHeights: ids.location('tsukikage_heights'),
  room203: ids.location('room_203'),
  broadcastHill: ids.location('broadcast_hill'),
} as const

export const characterIds = {
  sumi: ids.character('sumi'),
  akari: ids.character('akari'),
  kanade: ids.character('kanade'),
  ren: ids.character('ren'),
  koyomi: ids.character('koyomi'),
  minato: ids.character('minato'),
  tsuki: ids.character('tsuki'),
} as const

export const chapterIds = {
  day0: ids.chapter('day_0_transfer'),
  day1: ids.chapter('day_1_greetings'),
  day2: ids.chapter('day_2_erased_name'),
  day3: ids.chapter('day_3_silent_broadcast'),
  day4: ids.chapter('day_4_room_204'),
  day5: ids.chapter('day_5_memories'),
  day6: ids.chapter('day_6_thirteenth_notice'),
  day7: ids.chapter('day_7_broadcast_tower'),
} as const

export const objectiveIds = {
  d0Arrive: ids.objective('d0_arrive'),
  d0Register: ids.objective('d0_register'),
  d0Mailbox: ids.objective('d0_mailbox'),
  d1Greet: ids.objective('d1_greet_three'),
  d1VisitShop: ids.objective('d1_visit_shop'),
  d1StartErrand: ids.objective('d1_start_errand'),
  d2Ledger: ids.objective('d2_check_ledger'),
  d2History: ids.objective('d2_borrow_history'),
  d2Respond: ids.objective('d2_respond_to_sumi'),
  d3Cassette: ids.objective('d3_play_cassette'),
  d3Broadcast: ids.objective('d3_choose_broadcast_response'),
  d4Keys: ids.objective('d4_sort_keys'),
  d4Door: ids.objective('d4_find_door_outline'),
  d4Mailbox: ids.objective('d4_open_mailbox_bottom'),
  d5Testimony: ids.objective('d5_gather_testimony'),
  d5Intent: ids.objective('d5_choose_intent'),
  d6Notice: ids.objective('d6_read_thirteenth_notice'),
  d6Companion: ids.objective('d6_choose_companion'),
  d7Recording: ids.objective('d7_hear_final_recording'),
  d7Decision: ids.objective('d7_make_final_choice'),
} as const

export const sceneIds = {
  d0Station: ids.scene('d0_station_arrival'),
  d0TownHall: ids.scene('d0_town_hall'),
  d0Apartment: ids.scene('d0_apartment'),
  d1Street: ids.scene('d1_street_greetings'),
  d1Shop: ids.scene('d1_first_shop'),
  d2TownHall: ids.scene('d2_old_ledger'),
  d2Books: ids.scene('d2_town_history'),
  d3Cafe: ids.scene('d3_cassette'),
  d3Night: ids.scene('d3_broadcast'),
  d4Hallway: ids.scene('d4_hallway'),
  d4Mailbox: ids.scene('d4_double_bottom'),
  d5Testimony: ids.scene('d5_testimonies'),
  d6Board: ids.scene('d6_thirteenth_notice'),
  d6HillRoad: ids.scene('d6_hill_road'),
  d7Tower: ids.scene('d7_tower'),
  d7Decision: ids.scene('d7_decision'),
} as const

export const dialogueIds = {
  sumiD0: ids.dialogue('sumi_d0_registration'),
  sumiD2: ids.dialogue('sumi_d2_question'),
  sumiD5Low: ids.dialogue('sumi_d5_guarded'),
  sumiD5High: ids.dialogue('sumi_d5_trusted'),
  akariD1: ids.dialogue('akari_d1_bookshop'),
  akariD2: ids.dialogue('akari_d2_town_history'),
  akariD5Low: ids.dialogue('akari_d5_guarded'),
  akariD5High: ids.dialogue('akari_d5_trusted'),
  kanadeD1: ids.dialogue('kanade_d1_cafe'),
  kanadeD3: ids.dialogue('kanade_d3_cassette'),
  kanadeD5Low: ids.dialogue('kanade_d5_guarded'),
  kanadeD5High: ids.dialogue('kanade_d5_trusted'),
  renD1: ids.dialogue('ren_d1_warning'),
  renD3: ids.dialogue('ren_d3_response'),
  renD5Low: ids.dialogue('ren_d5_guarded'),
  renD5High: ids.dialogue('ren_d5_trusted'),
  renD6Companion: ids.dialogue('ren_d6_companion'),
  koyomiD0: ids.dialogue('koyomi_d0_key'),
  koyomiD4: ids.dialogue('koyomi_d4_keys'),
  koyomiD5Low: ids.dialogue('koyomi_d5_guarded'),
  koyomiD5High: ids.dialogue('koyomi_d5_trusted'),
  minatoD3: ids.dialogue('minato_d3_broadcast'),
  minatoD4: ids.dialogue('minato_d4_unsent_letter'),
  minatoD7Sparse: ids.dialogue('minato_d7_sparse_recording'),
  minatoD7Full: ids.dialogue('minato_d7_full_recording'),
  tsukiRepeat: ids.dialogue('tsuki_repeat'),
} as const

export const letterIds = {
  transferGuide: ids.letter('transfer_guide'),
  to204: ids.letter('to_room_204'),
  doNotDiscard: ids.letter('do_not_discard'),
  historyReturn: ids.letter('history_return_request'),
  cafeInvitation: ids.letter('cafe_night_invitation'),
  sumiMeeting: ids.letter('sumi_private_meeting'),
  minatoUnsent: ids.letter('minato_unsent'),
  renSafetyNote: ids.letter('ren_safety_note'),
  endingA: ids.letter('ending_a_welcome'),
  endingB: ids.letter('ending_b_carriage'),
  endingC: ids.letter('ending_c_first_delivery'),
  endingD: ids.letter('ending_d_faded_address'),
} as const

export const bulletinIds = {
  garbage: ids.bulletin('official_01_garbage'),
  streetlights: ids.bulletin('official_02_streetlights'),
  lostCat: ids.bulletin('official_03_lost_cat'),
  river: ids.bulletin('official_04_river_cleanup'),
  bookFair: ids.bulletin('official_05_book_fair'),
  cafeClosed: ids.bulletin('official_06_cafe_closed'),
  radioTest: ids.bulletin('official_07_radio_test'),
  towerClosed: ids.bulletin('official_08_tower_closed'),
  water: ids.bulletin('official_09_water_check'),
  lostItem: ids.bulletin('official_10_lost_item'),
  festival: ids.bulletin('official_11_festival'),
  lastTrain: ids.bulletin('official_12_last_train'),
  thirteenth: ids.bulletin('conditional_13_names'),
} as const

export const clueIds = {
  envelope204: ids.clue('envelope_204'),
  populationFlicker: ids.clue('population_flicker'),
  missingPage13: ids.clue('missing_page_13'),
  minatoBadge: ids.clue('minato_badge'),
  clock1113: ids.clue('clock_1113'),
  blueInk: ids.clue('blue_ink_correction'),
  mailboxFalseBottom: ids.clue('mailbox_false_bottom'),
  evacuationLog: ids.clue('evacuation_broadcast_log'),
  sumiPhoto: ids.clue('sumi_family_photo'),
  renFatherLog: ids.clue('ren_father_log'),
  cassetteBack: ids.clue('cassette_back_note'),
  oldFloorplan: ids.clue('old_floorplan'),
  thirteenthNotice: ids.clue('thirteenth_notice'),
  towerKey: ids.clue('tower_key'),
  unsentMoveOut: ids.clue('unsent_move_out_form'),
} as const

export const subEventIds = {
  tsukiCollar: ids.subEvent('tsuki_collar'),
  tornHistory: ids.subEvent('torn_town_history'),
  cafeCassette: ids.subEvent('cafe_cassette'),
  keySorting: ids.subEvent('key_sorting'),
} as const

export const subEventStageIds = {
  tsukiMeet: ids.subEventStage('tsuki_meet'),
  tsukiCollar: ids.subEventStage('tsuki_read_collar'),
  tsukiPath: ids.subEventStage('tsuki_follow_path'),
  historyPiece1: ids.subEventStage('history_piece_1'),
  historyPiece2: ids.subEventStage('history_piece_2'),
  historyPiece3: ids.subEventStage('history_piece_3'),
  cassettePlay: ids.subEventStage('cassette_play'),
  cassetteTurn: ids.subEventStage('cassette_turn'),
  cassetteListen: ids.subEventStage('cassette_listen'),
  keyGroup: ids.subEventStage('key_group'),
  keyMissing204: ids.subEventStage('key_missing_204'),
  keySmall: ids.subEventStage('key_small'),
} as const

export const investigationIds = {
  stationClock: ids.investigation('station_clock'),
  populationBoard: ids.investigation('population_board'),
  mailbox204: ids.investigation('mailbox_204'),
  ledger: ids.investigation('old_ledger'),
  historyPage: ids.investigation('history_page_13'),
  badge: ids.investigation('maintenance_badge'),
  blueCorrection: ids.investigation('blue_correction'),
  cassette: ids.investigation('cassette'),
  doorOutline: ids.investigation('door_outline'),
  mailboxBottom: ids.investigation('mailbox_bottom'),
  floorplan: ids.investigation('old_floorplan'),
  familyPhoto: ids.investigation('family_photo'),
  renLog: ids.investigation('ren_father_log'),
  towerFence: ids.investigation('tower_fence'),
  towerConsole: ids.investigation('tower_console'),
  noticeGap: ids.investigation('notice_gap'),
} as const

export const endingIds = {
  a: ids.ending('A'),
  b: ids.ending('B'),
  c: ids.ending('C'),
  d: ids.ending('D'),
} as const

export const achievementIds = {
  newResident: ids.achievement('new_resident'),
  goodNeighbor: ids.achievement('good_neighbor'),
  paperTrail: ids.achievement('paper_trail'),
  catFriend: ids.achievement('cat_friend'),
  silentListener: ids.achievement('silent_listener'),
  thirteenthReader: ids.achievement('thirteenth_reader'),
  endingA: ids.achievement('ending_a'),
  endingB: ids.achievement('ending_b'),
  endingC: ids.achievement('ending_c'),
} as const

export const flagIds = {
  registered: ids.flag('registered'),
  roomKeyReceived: ids.flag('room_key_received'),
  mailboxOpened: ids.flag('mailbox_opened'),
  shopErrandStarted: ids.flag('shop_errand_started'),
  sumiAnswered: ids.flag('sumi_answered'),
  broadcastReplied: ids.flag('broadcast_replied'),
  broadcastListened: ids.flag('broadcast_listened'),
  broadcastCut: ids.flag('broadcast_cut'),
  doorOutlineFound: ids.flag('door_outline_found'),
  doubleBottomOpened: ids.flag('double_bottom_opened'),
  testimonyGathered: ids.flag('testimony_gathered'),
  intentPublic: ids.flag('intent_public'),
  intentLocal: ids.flag('intent_local'),
  intentMinato: ids.flag('intent_minato'),
  companionAsked: ids.flag('companion_asked'),
  companionAlone: ids.flag('companion_alone'),
  finalRecordingHeard: ids.flag('final_recording_heard'),
  finalDecisionMade: ids.flag('final_decision_made'),
  tsukiCollarRead: ids.flag('tsuki_collar_read'),
  historyPiece1Found: ids.flag('history_piece_1_found'),
  historyPiece2Found: ids.flag('history_piece_2_found'),
  historyPiece3Found: ids.flag('history_piece_3_found'),
  cassetteTurned: ids.flag('cassette_turned'),
  keysGrouped: ids.flag('keys_grouped'),
  key204Missing: ids.flag('key_204_missing'),
  smallKeyFound: ids.flag('small_key_found'),
  minatoWishUnderstood: ids.flag('minato_wish_understood'),
  room204RecordRecovered: ids.flag('room_204_record_recovered'),
  allAnonymousLettersRead: ids.flag('all_anonymous_letters_read'),
  thirteenthNoticeVisible: ids.flag('thirteenth_notice_visible'),
} as const
