import {
  characterIds,
  clueIds,
  dialogueIds,
  flagIds,
  letterIds,
  locationIds,
  subEventIds,
} from './contentIds'
import { ids } from './types'
import type {
  CharacterId,
  Condition,
  Dialogue,
  DialogueChoice,
  DialogueChoiceNode,
  DialogueId,
  DialogueLineNode,
  DialogueNodeId,
  Effect,
  ValueTone,
} from './types'

type Mood = DialogueLineNode['mood']

const nodeId = (dialogueId: DialogueId, suffix: string): DialogueNodeId =>
  ids.dialogueNode(`${dialogueId}:${suffix}`)

const destination = (dialogueId: DialogueId, suffix: string): DialogueNodeId | 'end' =>
  suffix === 'end' ? 'end' : nodeId(dialogueId, suffix)

const line = (
  dialogueId: DialogueId,
  suffix: string,
  speakerId: CharacterId | 'narrator',
  text: string,
  mood: Mood,
  next: string,
  effects: readonly Effect[] = [],
): DialogueLineNode => ({
  id: nodeId(dialogueId, suffix),
  kind: 'line',
  speakerId,
  text,
  mood,
  nextNodeId: destination(dialogueId, next),
  effects,
})

const option = (
  dialogueId: DialogueId,
  id: string,
  text: string,
  tone: ValueTone,
  next: string,
  effects: readonly Effect[],
  condition: Condition = { kind: 'always' },
): DialogueChoice => ({
  id,
  text,
  tone,
  condition,
  nextNodeId: destination(dialogueId, next),
  effects,
})

const choice = (
  dialogueId: DialogueId,
  suffix: string,
  speakerId: CharacterId | 'narrator',
  text: string,
  mood: Mood,
  choices: readonly DialogueChoice[],
): DialogueChoiceNode => ({
  id: nodeId(dialogueId, suffix),
  kind: 'choice',
  speakerId,
  text,
  mood,
  choices,
})

const sumiDialogues = [
  {
    id: dialogueIds.sumiD0,
    title: '町が忘れない字',
    characterId: characterIds.sumi,
    day: 0,
    locationId: locationIds.townHall,
    priority: 100,
    conditions: { kind: 'flag', flagId: flagIds.registered, value: false },
    entryNodeId: nodeId(dialogueIds.sumiD0, 'welcome'),
    nodes: [
      line(
        dialogueIds.sumiD0,
        'welcome',
        characterIds.sumi,
        'ようこそ、月影町へ。お名前は、町が忘れないよう、丁寧に書いてくださいね。',
        'warm',
        'population',
      ),
      line(
        dialogueIds.sumiD0,
        'population',
        characterIds.sumi,
        '表示は1,284人です。あなたを足せば……機械が決めるまで、少し待ちましょう。',
        'uneasy',
        'response',
        [{ kind: 'discoverClue', clueId: clueIds.populationFlicker }],
      ),
      choice(
        dialogueIds.sumiD0,
        'response',
        'narrator',
        '澄は人口表示から目を戻し、転入届を差し出した。',
        'neutral',
        [
          option(
            dialogueIds.sumiD0,
            'accept',
            '「これから、よろしくお願いします」',
            'accept',
            'key',
            [{ kind: 'addTrust', characterId: characterIds.sumi, amount: 1 }],
          ),
          option(
            dialogueIds.sumiD0,
            'verify',
            '「台帳の人数とは合っていますか」',
            'verify',
            'key',
            [{ kind: 'addTrust', characterId: characterIds.sumi, amount: 1 }],
          ),
          option(
            dialogueIds.sumiD0,
            'distance',
            '「手続きだけ終えたいです」',
            'distance',
            'key',
            [],
          ),
        ],
      ),
      line(
        dialogueIds.sumiD0,
        'key',
        characterIds.sumi,
        'こちらが住民票と203号室の鍵です。人数のことは、明日も気になったら聞いてください。',
        'neutral',
        'end',
        [
          { kind: 'setFlag', flagId: flagIds.registered, value: true },
          { kind: 'setFlag', flagId: flagIds.roomKeyReceived, value: true },
          { kind: 'deliverLetter', letterId: letterIds.transferGuide },
        ],
      ),
    ],
    journalSummary: '御影澄から住民票と203号室の鍵を受け取った。人口表示は一人ぶん揺れた。',
  },
  {
    id: dialogueIds.sumiD2,
    title: '消された行の前で',
    characterId: characterIds.sumi,
    day: 2,
    locationId: locationIds.townHall,
    priority: 90,
    conditions: { kind: 'clue', clueId: clueIds.blueInk },
    entryNodeId: nodeId(dialogueIds.sumiD2, 'ledger'),
    nodes: [
      line(
        dialogueIds.sumiD2,
        'ledger',
        characterIds.sumi,
        'その訂正を、私が書いたと思いましたか。色は同じです。そう見えても仕方ありません。',
        'guarded',
        'response',
      ),
      choice(
        dialogueIds.sumiD2,
        'response',
        'narrator',
        '青いペン先が、台帳から少し離れた。',
        'neutral',
        [
          option(
            dialogueIds.sumiD2,
            'accept',
            '「黙った理由を、あなたの言葉で聞きたい」',
            'accept',
            'truth',
            [
              { kind: 'addTrust', characterId: characterIds.sumi, amount: 2 },
              { kind: 'setFlag', flagId: flagIds.sumiAnswered, value: true },
            ],
          ),
          option(
            dialogueIds.sumiD2,
            'verify',
            '「筆跡と命令印を一緒に確かめたい」',
            'verify',
            'truth',
            [
              { kind: 'addTrust', characterId: characterIds.sumi, amount: 1 },
              { kind: 'setFlag', flagId: flagIds.sumiAnswered, value: true },
            ],
          ),
          option(
            dialogueIds.sumiD2,
            'distance',
            '「今は決めません。調査を続けます」',
            'distance',
            'pause',
            [{ kind: 'setFlag', flagId: flagIds.sumiAnswered, value: true }],
          ),
        ],
      ),
      line(
        dialogueIds.sumiD2,
        'truth',
        characterIds.sumi,
        '書いたのは前任者です。私は消された行を知りながら、元へ戻せずにいました。兄の行です。',
        'uneasy',
        'ink',
      ),
      line(
        dialogueIds.sumiD2,
        'pause',
        characterIds.sumi,
        'それでいいと思います。私も、長いあいだ決められませんでした。資料箱の鍵は開けます。',
        'neutral',
        'ink',
      ),
      line(
        dialogueIds.sumiD2,
        'ink',
        characterIds.sumi,
        '色だけで人を決めないでくださって、ありがとうございます。命令印も日記に写してください。',
        'warm',
        'end',
        [{ kind: 'discoverClue', clueId: clueIds.blueInk }],
      ),
    ],
    journalSummary: '青い訂正は澄の筆跡ではない。星見湊は澄の兄で、前任者が転出と記した。',
  },
  {
    id: dialogueIds.sumiD5Low,
    title: '窓口で話せる範囲',
    characterId: characterIds.sumi,
    day: 5,
    locationId: locationIds.townHall,
    priority: 70,
    conditions: {
      kind: 'all',
      conditions: [
        { kind: 'day', comparison: 'gte', value: 5 },
        { kind: 'trust', characterId: characterIds.sumi, comparison: 'lte', value: 2 },
      ],
    },
    entryNodeId: nodeId(dialogueIds.sumiD5Low, 'guarded'),
    nodes: [
      line(
        dialogueIds.sumiD5Low,
        'guarded',
        characterIds.sumi,
        '兄の記録が変えられたことは事実です。でも、窓口で家族の話まで公開はできません。',
        'guarded',
        'intent',
        [{ kind: 'incrementStat', statId: 'testimoniesHeard', amount: 1 }],
      ),
      choice(
        dialogueIds.sumiD5Low,
        'intent',
        characterIds.sumi,
        '集めた記録を、あなたはどうしたいですか。今の考えで構いません。',
        'neutral',
        [
          option(dialogueIds.sumiD5Low, 'public', '町の外でも読める記録にしたい', 'verify', 'end', [
            { kind: 'setFlag', flagId: flagIds.intentPublic, value: true },
            { kind: 'setFlag', flagId: flagIds.testimonyGathered, value: true },
          ]),
          option(dialogueIds.sumiD5Low, 'local', 'まず町の人へ名前を返したい', 'accept', 'end', [
            { kind: 'setFlag', flagId: flagIds.intentLocal, value: true },
            { kind: 'setFlag', flagId: flagIds.testimonyGathered, value: true },
          ]),
          option(dialogueIds.sumiD5Low, 'minato', '湊本人が望んだ形を探したい', 'distance', 'end', [
            { kind: 'setFlag', flagId: flagIds.intentMinato, value: true },
            { kind: 'setFlag', flagId: flagIds.testimonyGathered, value: true },
          ]),
        ],
      ),
    ],
    journalSummary: '澄は記録改変を認めたが、家族の話はまだ伏せた。自分の方針を伝えた。',
  },
  {
    id: dialogueIds.sumiD5High,
    title: '消せなかった写真',
    characterId: characterIds.sumi,
    day: 5,
    locationId: locationIds.townHall,
    priority: 95,
    conditions: {
      kind: 'all',
      conditions: [
        { kind: 'day', comparison: 'gte', value: 5 },
        { kind: 'trust', characterId: characterIds.sumi, comparison: 'gte', value: 3 },
      ],
    },
    entryNodeId: nodeId(dialogueIds.sumiD5High, 'photo'),
    nodes: [
      line(
        dialogueIds.sumiD5High,
        'photo',
        characterIds.sumi,
        'これが兄の湊です。町が名前を消した日も、私はこの写真だけ捨てられませんでした。',
        'uneasy',
        'reason',
        [
          { kind: 'discoverClue', clueId: clueIds.sumiPhoto },
          { kind: 'incrementStat', statId: 'testimoniesHeard', amount: 1 },
        ],
      ),
      line(
        dialogueIds.sumiD5High,
        'reason',
        characterIds.sumi,
        '避難した人を守り、責任の矛先を止めたい気持ちもありました。沈黙は、正しさではありません。',
        'resolute',
        'intent',
      ),
      choice(
        dialogueIds.sumiD5High,
        'intent',
        characterIds.sumi,
        '兄の名前を戻すなら、どこへ戻すべきだと思いますか。',
        'neutral',
        [
          option(dialogueIds.sumiD5High, 'public', '町の外まで届く記録へ', 'verify', 'close', [
            { kind: 'setFlag', flagId: flagIds.intentPublic, value: true },
          ]),
          option(dialogueIds.sumiD5High, 'local', '町の台帳と人の会話へ', 'accept', 'close', [
            { kind: 'setFlag', flagId: flagIds.intentLocal, value: true },
            { kind: 'addTrust', characterId: characterIds.sumi, amount: 1 },
          ]),
          option(dialogueIds.sumiD5High, 'minato', '湊の私信が届く仕組みへ', 'distance', 'close', [
            { kind: 'setFlag', flagId: flagIds.intentMinato, value: true },
          ]),
        ],
      ),
      line(
        dialogueIds.sumiD5High,
        'close',
        characterIds.sumi,
        'どれにも、戻る名前と離れる名前がありますね。私は、選んだ後の町にも残ります。',
        'warm',
        'end',
        [{ kind: 'setFlag', flagId: flagIds.testimonyGathered, value: true }],
      ),
    ],
    journalSummary: '澄は湊の妹だった。記録改変には住民保護と責任回避の両方があった。',
  },
] as const satisfies readonly Dialogue[]

const akariDialogues = [
  {
    id: dialogueIds.akariD1,
    title: '欠けた本も本のうち',
    characterId: characterIds.akari,
    day: 1,
    locationId: locationIds.toukaBooks,
    priority: 80,
    conditions: { kind: 'day', comparison: 'gte', value: 1 },
    entryNodeId: nodeId(dialogueIds.akariD1, 'greeting'),
    nodes: [
      line(
        dialogueIds.akariD1,
        'greeting',
        characterIds.akari,
        '転入した方ね。本を探す顔と、町を探す顔は少し違う。あなたは両方に見えます。',
        'warm',
        'choice',
      ),
      choice(
        dialogueIds.akariD1,
        'choice',
        characterIds.akari,
        '十三年前の町史は欠けています。それでも借りますか。',
        'neutral',
        [
          option(dialogueIds.akariD1, 'accept', '欠けたところも含めて借りる', 'accept', 'book', [
            { kind: 'addTrust', characterId: characterIds.akari, amount: 1 },
            { kind: 'startSubEvent', subEventId: subEventIds.tornHistory },
            { kind: 'setFlag', flagId: flagIds.shopErrandStarted, value: true },
          ]),
          option(dialogueIds.akariD1, 'verify', '欠けた理由から確かめる', 'verify', 'book', [
            { kind: 'addTrust', characterId: characterIds.akari, amount: 1 },
            { kind: 'startSubEvent', subEventId: subEventIds.tornHistory },
            { kind: 'setFlag', flagId: flagIds.shopErrandStarted, value: true },
          ]),
          option(
            dialogueIds.akariD1,
            'distance',
            '今日は紙片の形だけ記録する',
            'distance',
            'book',
            [
              { kind: 'startSubEvent', subEventId: subEventIds.tornHistory },
              { kind: 'setFlag', flagId: flagIds.shopErrandStarted, value: true },
            ],
          ),
        ],
      ),
      line(
        dialogueIds.akariD1,
        'book',
        characterIds.akari,
        '本は、読まれなくなっても書かれたことまで消えません。町も、たぶん同じです。',
        'warm',
        'end',
        [{ kind: 'incrementStat', statId: 'spokenCharacters', amount: 1 }],
      ),
    ],
    journalSummary: '灯下書房には欠けた町史がある。灯は、欠けた部分も資料として扱っている。',
  },
  {
    id: dialogueIds.akariD2,
    title: '保守員の欄',
    characterId: characterIds.akari,
    day: 2,
    locationId: locationIds.toukaBooks,
    priority: 90,
    conditions: { kind: 'clue', clueId: clueIds.missingPage13 },
    entryNodeId: nodeId(dialogueIds.akariD2, 'badge'),
    nodes: [
      line(
        dialogueIds.akariD2,
        'badge',
        characterIds.akari,
        '星見湊。放送塔の保守員でした。名札の写真を剥がしても、刻印までは消せなかった。',
        'neutral',
        'choice',
        [{ kind: 'discoverClue', clueId: clueIds.minatoBadge }],
      ),
      choice(
        dialogueIds.akariD2,
        'choice',
        characterIds.akari,
        '切られたページを見つけたら、どう扱いますか。',
        'neutral',
        [
          option(dialogueIds.akariD2, 'accept', '元の本へ戻せる形で守る', 'accept', 'end', [
            { kind: 'addTrust', characterId: characterIds.akari, amount: 2 },
          ]),
          option(dialogueIds.akariD2, 'verify', '複製して切り口も記録する', 'verify', 'end', [
            { kind: 'addTrust', characterId: characterIds.akari, amount: 2 },
          ]),
          option(
            dialogueIds.akariD2,
            'distance',
            'まだ誰にも見せず保管する',
            'distance',
            'end',
            [],
          ),
        ],
      ),
    ],
    journalSummary: '星見湊は放送塔の保守員だった。町史の切り口も記録として残す必要がある。',
  },
  {
    id: dialogueIds.akariD5Low,
    title: '棚から渡せる証言',
    characterId: characterIds.akari,
    day: 5,
    locationId: locationIds.toukaBooks,
    priority: 65,
    conditions: {
      kind: 'all',
      conditions: [
        { kind: 'day', comparison: 'gte', value: 5 },
        { kind: 'trust', characterId: characterIds.akari, comparison: 'lte', value: 2 },
      ],
    },
    entryNodeId: nodeId(dialogueIds.akariD5Low, 'shelf'),
    nodes: [
      line(
        dialogueIds.akariD5Low,
        'shelf',
        characterIds.akari,
        '私が言えるのは、本が捨てられかけたことまで。誰が紙片を分けたかは、まだ伏せます。',
        'guarded',
        'end',
        [{ kind: 'incrementStat', statId: 'testimoniesHeard', amount: 1 }],
      ),
    ],
    journalSummary: '灯は町史が捨てられかけたと証言した。紙片を分けた人物は伏せている。',
  },
  {
    id: dialogueIds.akariD5High,
    title: '拾った十三ページ',
    characterId: characterIds.akari,
    day: 5,
    locationId: locationIds.toukaBooks,
    priority: 92,
    conditions: {
      kind: 'all',
      conditions: [
        { kind: 'day', comparison: 'gte', value: 5 },
        { kind: 'trust', characterId: characterIds.akari, comparison: 'gte', value: 3 },
      ],
    },
    entryNodeId: nodeId(dialogueIds.akariD5High, 'confession'),
    nodes: [
      line(
        dialogueIds.akariD5High,
        'confession',
        characterIds.akari,
        '紙片を分けたのは私です。捨てる命令から守るには、一冊のままでは目立ちすぎました。',
        'resolute',
        'cost',
        [{ kind: 'incrementStat', statId: 'testimoniesHeard', amount: 1 }],
      ),
      line(
        dialogueIds.akariD5High,
        'cost',
        characterIds.akari,
        '守ったつもりで、十三年も読めなくした。善意も、長く閉じれば別の影を作ります。',
        'uneasy',
        'choice',
      ),
      choice(
        dialogueIds.akariD5High,
        'choice',
        characterIds.akari,
        '復元した町史は、どこに置くのがよいでしょう。',
        'neutral',
        [
          option(
            dialogueIds.akariD5High,
            'accept',
            '町の棚へ戻し、誰でも読めるようにする',
            'accept',
            'end',
            [{ kind: 'addTrust', characterId: characterIds.akari, amount: 1 }],
          ),
          option(dialogueIds.akariD5High, 'verify', '複製を町の外にも残す', 'verify', 'end', []),
          option(
            dialogueIds.akariD5High,
            'distance',
            '原本は閉じ、目録だけ公開する',
            'distance',
            'end',
            [],
          ),
        ],
      ),
    ],
    journalSummary:
      '灯が町史を三枚へ分けて守った。保護は同時に、十三年間読めなくする結果になった。',
  },
] as const satisfies readonly Dialogue[]

const kanadeDialogues = [
  {
    id: dialogueIds.kanadeD1,
    title: '静かな町の音',
    characterId: characterIds.kanade,
    day: 1,
    locationId: locationIds.yoimachiCafe,
    priority: 80,
    conditions: { kind: 'day', comparison: 'gte', value: 1 },
    entryNodeId: nodeId(dialogueIds.kanadeD1, 'soda'),
    nodes: [
      line(
        dialogueIds.kanadeD1,
        'soda',
        characterIds.kanade,
        '転入のお祝いに、月色クリームソーダ。普通のソーダだけど、名前は大事だからね。',
        'warm',
        'sounds',
      ),
      line(
        dialogueIds.kanadeD1,
        'sounds',
        characterIds.kanade,
        '静かな町ほど、みんな音を聞いてる。電車、雨……それから、聞こえないはずの放送。',
        'uneasy',
        'choice',
      ),
      choice(dialogueIds.kanadeD1, 'choice', characterIds.kanade, '怖い噂だと思う？', 'neutral', [
        option(
          dialogueIds.kanadeD1,
          'accept',
          '怖かった人の話なら、笑わずに聞く',
          'accept',
          'end',
          [
            { kind: 'addTrust', characterId: characterIds.kanade, amount: 2 },
            { kind: 'incrementStat', statId: 'spokenCharacters', amount: 1 },
          ],
        ),
        option(dialogueIds.kanadeD1, 'verify', '放送があった記録を確かめたい', 'verify', 'end', [
          { kind: 'addTrust', characterId: characterIds.kanade, amount: 1 },
          { kind: 'incrementStat', statId: 'spokenCharacters', amount: 1 },
        ]),
        option(dialogueIds.kanadeD1, 'distance', '今日はソーダの話だけにする', 'distance', 'end', [
          { kind: 'incrementStat', statId: 'spokenCharacters', amount: 1 },
        ]),
      ]),
    ],
    journalSummary: '奏は幼い頃、聞こえないはずの夜間放送を聞いた。宵待に古いカセットがある。',
  },
  {
    id: dialogueIds.kanadeD3,
    title: '十二回の後',
    characterId: characterIds.kanade,
    day: 3,
    locationId: locationIds.yoimachiCafe,
    priority: 100,
    conditions: { kind: 'day', comparison: 'gte', value: 3 },
    entryNodeId: nodeId(dialogueIds.kanadeD3, 'play'),
    nodes: [
      line(
        dialogueIds.kanadeD3,
        'play',
        characterIds.kanade,
        '再生するね。十二回鳴った後が本番。でも、聞きたくなくなったら止めていいから。',
        'guarded',
        'broadcast',
        [{ kind: 'startSubEvent', subEventId: subEventIds.cafeCassette }],
      ),
      line(
        dialogueIds.kanadeD3,
        'broadcast',
        characterIds.minato,
        '月影荘二〇四号室の方へ。あなたの転入届を、お預かりしています。',
        'uneasy',
        'response',
      ),
      choice(
        dialogueIds.kanadeD3,
        'response',
        'narrator',
        'ノイズの奥で、返事を待つような空白が続く。',
        'uneasy',
        [
          option(dialogueIds.kanadeD3, 'reply', '「聞こえています」と返す', 'accept', 'after', [
            { kind: 'setFlag', flagId: flagIds.broadcastReplied, value: true },
          ]),
          option(dialogueIds.kanadeD3, 'listen', '黙って最後まで聞く', 'verify', 'after', [
            { kind: 'setFlag', flagId: flagIds.broadcastListened, value: true },
            { kind: 'addTrust', characterId: characterIds.kanade, amount: 1 },
            { kind: 'discoverClue', clueId: clueIds.evacuationLog },
          ]),
          option(dialogueIds.kanadeD3, 'cut', '電源を切る', 'distance', 'after', [
            { kind: 'setFlag', flagId: flagIds.broadcastCut, value: true },
          ]),
        ],
      ),
      line(
        dialogueIds.kanadeD3,
        'after',
        characterIds.kanade,
        '大丈夫。返事をしても、しなくても、止めても、今ここにいることは変わらないよ。',
        'warm',
        'end',
      ),
    ],
    journalSummary: '11時13分、204号室の転入届を預かっているという放送を聞いた。',
  },
  {
    id: dialogueIds.kanadeD5Low,
    title: '聞いたことだけ',
    characterId: characterIds.kanade,
    day: 5,
    locationId: locationIds.yoimachiCafe,
    priority: 65,
    conditions: {
      kind: 'all',
      conditions: [
        { kind: 'day', comparison: 'gte', value: 5 },
        { kind: 'trust', characterId: characterIds.kanade, comparison: 'lte', value: 2 },
      ],
    },
    entryNodeId: nodeId(dialogueIds.kanadeD5Low, 'sound'),
    nodes: [
      line(
        dialogueIds.kanadeD5Low,
        'sound',
        characterIds.kanade,
        '私が言えるのは、子どもの頃にも同じ声を聞いたこと。返事のことは、まだ話せない。',
        'guarded',
        'end',
        [{ kind: 'incrementStat', statId: 'testimoniesHeard', amount: 1 }],
      ),
    ],
    journalSummary: '奏は幼い頃にも同じ放送を聞いたが、その夜の行動はまだ話せない。',
  },
  {
    id: dialogueIds.kanadeD5High,
    title: '返事をしたかもしれない夜',
    characterId: characterIds.kanade,
    day: 5,
    locationId: locationIds.yoimachiCafe,
    priority: 92,
    conditions: {
      kind: 'all',
      conditions: [
        { kind: 'day', comparison: 'gte', value: 5 },
        { kind: 'trust', characterId: characterIds.kanade, comparison: 'gte', value: 3 },
      ],
    },
    entryNodeId: nodeId(dialogueIds.kanadeD5High, 'memory'),
    nodes: [
      line(
        dialogueIds.kanadeD5High,
        'memory',
        characterIds.kanade,
        '子どもの私、たぶん返事をした。でも何も起きなかった。ただ、名前を忘れる夢を見た。',
        'uneasy',
        'meaning',
        [{ kind: 'incrementStat', statId: 'testimoniesHeard', amount: 1 }],
      ),
      line(
        dialogueIds.kanadeD5High,
        'meaning',
        characterIds.kanade,
        'だから放送を怪物にしたくない。怖がった私も、誰かを呼んだ湊さんも嘘になるから。',
        'resolute',
        'choice',
      ),
      choice(
        dialogueIds.kanadeD5High,
        'choice',
        characterIds.kanade,
        'あの声を、これからどう聞きたい？',
        'neutral',
        [
          option(
            dialogueIds.kanadeD5High,
            'accept',
            '町の人が名前を思い出す声として',
            'accept',
            'end',
            [{ kind: 'addTrust', characterId: characterIds.kanade, amount: 1 }],
          ),
          option(
            dialogueIds.kanadeD5High,
            'verify',
            '録音として残し、誰でも確かめられるように',
            'verify',
            'end',
            [],
          ),
          option(
            dialogueIds.kanadeD5High,
            'distance',
            '必要な私信だけにして、普段は止める',
            'distance',
            'end',
            [],
          ),
        ],
      ),
    ],
    journalSummary: '奏は幼い頃に返事をしたかもしれない。放送を怪物だけの話にしたくないと語った。',
  },
] as const satisfies readonly Dialogue[]

const renDialogues = [
  {
    id: dialogueIds.renD1,
    title: '帰る道の忠告',
    characterId: characterIds.ren,
    day: 1,
    locationId: locationIds.mainStreet,
    priority: 75,
    conditions: { kind: 'day', comparison: 'gte', value: 1 },
    entryNodeId: nodeId(dialogueIds.renD1, 'warning'),
    nodes: [
      line(
        dialogueIds.renD1,
        'warning',
        characterIds.ren,
        '知らないものを追うのは止めない。ただ、帰る場所まで見失うな。丘は崩れやすい。',
        'guarded',
        'choice',
      ),
      choice(dialogueIds.renD1, 'choice', characterIds.ren, '立入禁止の札を見たか。', 'neutral', [
        option(dialogueIds.renD1, 'accept', '札に従い、行く時は声をかける', 'accept', 'end', [
          { kind: 'addTrust', characterId: characterIds.ren, amount: 2 },
          { kind: 'incrementStat', statId: 'spokenCharacters', amount: 1 },
        ]),
        option(dialogueIds.renD1, 'verify', '危険な場所と理由を地図で確かめる', 'verify', 'end', [
          { kind: 'addTrust', characterId: characterIds.ren, amount: 1 },
          { kind: 'incrementStat', statId: 'spokenCharacters', amount: 1 },
        ]),
        option(dialogueIds.renD1, 'distance', '丘へ行く予定はないとだけ答える', 'distance', 'end', [
          { kind: 'incrementStat', statId: 'spokenCharacters', amount: 1 },
        ]),
      ]),
    ],
    journalSummary: '榊巡査は放送塔の斜面を警戒している。無断で柵を越えないよう忠告された。',
  },
  {
    id: dialogueIds.renD3,
    title: '応答の記録',
    characterId: characterIds.ren,
    day: 3,
    locationId: locationIds.mainStreet,
    priority: 88,
    conditions: {
      kind: 'any',
      conditions: [
        { kind: 'flag', flagId: flagIds.broadcastReplied, value: true },
        { kind: 'flag', flagId: flagIds.broadcastListened, value: true },
        { kind: 'flag', flagId: flagIds.broadcastCut, value: true },
      ],
    },
    entryNodeId: nodeId(dialogueIds.renD3, 'ask'),
    nodes: [
      line(
        dialogueIds.renD3,
        'ask',
        characterIds.ren,
        '昨夜の放送を聞いたな。何をしたか責める気はない。正確に記録したい。',
        'neutral',
        'answer',
      ),
      choice(
        dialogueIds.renD3,
        'answer',
        'narrator',
        '自分が選んだ行動を、そのまま伝える。',
        'neutral',
        [
          option(
            dialogueIds.renD3,
            'replied',
            '返事をした',
            'accept',
            'advice',
            [{ kind: 'addTrust', characterId: characterIds.ren, amount: 1 }],
            { kind: 'flag', flagId: flagIds.broadcastReplied, value: true },
          ),
          option(
            dialogueIds.renD3,
            'listened',
            '黙って最後まで聞いた',
            'verify',
            'advice',
            [{ kind: 'addTrust', characterId: characterIds.ren, amount: 2 }],
            { kind: 'flag', flagId: flagIds.broadcastListened, value: true },
          ),
          option(
            dialogueIds.renD3,
            'cut',
            '電源を切った',
            'distance',
            'advice',
            [{ kind: 'addTrust', characterId: characterIds.ren, amount: 2 }],
            { kind: 'flag', flagId: flagIds.broadcastCut, value: true },
          ),
        ],
      ),
      line(
        dialogueIds.renD3,
        'advice',
        characterIds.ren,
        '分かった。次に聞いても、一人で確かめに行くな。記録は行動より先に残してくれ。',
        'warm',
        'end',
      ),
    ],
    journalSummary: '夜の放送への対応を榊へ伝えた。榊は非難せず、安全と記録を優先した。',
  },
  {
    id: dialogueIds.renD5Low,
    title: '規則の側から',
    characterId: characterIds.ren,
    day: 5,
    locationId: locationIds.mainStreet,
    priority: 64,
    conditions: {
      kind: 'all',
      conditions: [
        { kind: 'day', comparison: 'gte', value: 5 },
        { kind: 'trust', characterId: characterIds.ren, comparison: 'lte', value: 2 },
      ],
    },
    entryNodeId: nodeId(dialogueIds.renD5Low, 'rule'),
    nodes: [
      line(
        dialogueIds.renD5Low,
        'rule',
        characterIds.ren,
        '父が記録処理に立ち会ったのは事実だ。日誌は、出所を確かめてから見せる。',
        'guarded',
        'end',
        [{ kind: 'incrementStat', statId: 'testimoniesHeard', amount: 1 }],
      ),
    ],
    journalSummary: '榊の父は記録処理に立ち会った。日誌を見るには、証拠の出所を示す必要がある。',
  },
  {
    id: dialogueIds.renD5High,
    title: '父が正しいと書けなかったこと',
    characterId: characterIds.ren,
    day: 5,
    locationId: locationIds.mainStreet,
    priority: 91,
    conditions: {
      kind: 'all',
      conditions: [
        { kind: 'day', comparison: 'gte', value: 5 },
        { kind: 'trust', characterId: characterIds.ren, comparison: 'gte', value: 3 },
      ],
    },
    entryNodeId: nodeId(dialogueIds.renD5High, 'journal'),
    nodes: [
      line(
        dialogueIds.renD5High,
        'journal',
        characterIds.ren,
        '父の日誌だ。命令に従ったとある。その下に、正しかったとは書けない、とも。',
        'uneasy',
        'choice',
        [
          { kind: 'discoverClue', clueId: clueIds.renFatherLog },
          { kind: 'incrementStat', statId: 'testimoniesHeard', amount: 1 },
        ],
      ),
      choice(
        dialogueIds.renD5High,
        'choice',
        characterIds.ren,
        '父の名も記録へ出る。それでも外へ持ち出すか。',
        'guarded',
        [
          option(
            dialogueIds.renD5High,
            'accept',
            '責めるためでなく、経緯ごと残す',
            'accept',
            'end',
            [{ kind: 'addTrust', characterId: characterIds.ren, amount: 1 }],
          ),
          option(
            dialogueIds.renD5High,
            'verify',
            '命令系統と筆跡を揃えてから判断する',
            'verify',
            'end',
            [{ kind: 'addTrust', characterId: characterIds.ren, amount: 1 }],
          ),
          option(
            dialogueIds.renD5High,
            'distance',
            '町の中だけで読み継ぐ選択も残す',
            'distance',
            'end',
            [],
          ),
        ],
      ),
    ],
    journalSummary: '榊の父は命令で記録を変え、日誌に後悔を残した。誰か一人の悪意ではない。',
  },
  {
    id: dialogueIds.renD6Companion,
    title: '丘へ向かう前に',
    characterId: characterIds.ren,
    day: 6,
    locationId: locationIds.bulletinBoard,
    priority: 105,
    conditions: { kind: 'clue', clueId: clueIds.thirteenthNotice },
    entryNodeId: nodeId(dialogueIds.renD6Companion, 'route'),
    nodes: [
      line(
        dialogueIds.renD6Companion,
        'route',
        characterIds.ren,
        '保守道は確認した。同行するなら灯りを持つ。一人で行くなら、戻る時刻を決めてくれ。',
        'resolute',
        'choice',
      ),
      choice(
        dialogueIds.renD6Companion,
        'choice',
        characterIds.ren,
        '安全のための選択だ。どちらでも、塔の中で決めることまでは口を出さない。',
        'neutral',
        [
          option(dialogueIds.renD6Companion, 'together', '同行を頼む', 'accept', 'end', [
            { kind: 'setFlag', flagId: flagIds.companionAsked, value: true },
            { kind: 'addTrust', characterId: characterIds.ren, amount: 1 },
          ]),
          option(
            dialogueIds.renD6Companion,
            'alone',
            '一人で行き、帰る時刻を伝える',
            'verify',
            'end',
            [{ kind: 'setFlag', flagId: flagIds.companionAlone, value: true }],
          ),
        ],
      ),
    ],
    journalSummary: '放送塔へは榊と同行しても、一人で保守道を使ってもよい。最終判断は任される。',
  },
] as const satisfies readonly Dialogue[]

const koyomiDialogues = [
  {
    id: dialogueIds.koyomiD0,
    title: '偶数が少し苦手な建物',
    characterId: characterIds.koyomi,
    day: 0,
    locationId: locationIds.tsukikageHeights,
    priority: 95,
    conditions: { kind: 'flag', flagId: flagIds.roomKeyReceived, value: true },
    entryNodeId: nodeId(dialogueIds.koyomiD0, 'key'),
    nodes: [
      line(
        dialogueIds.koyomiD0,
        'key',
        characterIds.koyomi,
        'お部屋は203号室です。204？　この建物は、偶数が少し苦手なのかもしれませんね。',
        'warm',
        'clock',
      ),
      line(
        dialogueIds.koyomiD0,
        'clock',
        characterIds.koyomi,
        '駅の時計も見ましたか。11時13分は、昔の住人が帰りそこねた時刻だそうです。',
        'neutral',
        'choice',
        [{ kind: 'discoverClue', clueId: clueIds.clock1113 }],
      ),
      choice(
        dialogueIds.koyomiD0,
        'choice',
        characterIds.koyomi,
        '204を、ない部屋だと思いますか。',
        'neutral',
        [
          option(
            dialogueIds.koyomiD0,
            'accept',
            '郵便物があるなら、誰かの場所だったと思う',
            'accept',
            'mailbox',
            [{ kind: 'addTrust', characterId: characterIds.koyomi, amount: 2 }],
          ),
          option(
            dialogueIds.koyomiD0,
            'verify',
            '間取りと改装記録を確かめたい',
            'verify',
            'mailbox',
            [{ kind: 'addTrust', characterId: characterIds.koyomi, amount: 1 }],
          ),
          option(
            dialogueIds.koyomiD0,
            'distance',
            '今は203号室だけ分かればいい',
            'distance',
            'mailbox',
            [],
          ),
        ],
      ),
      line(
        dialogueIds.koyomiD0,
        'mailbox',
        characterIds.koyomi,
        'では、鍵を。共同郵便受けも見てください。部屋より先に、手紙が住人を覚えることがあります。',
        'warm',
        'end',
      ),
    ],
    journalSummary: 'こよみは204を否定せず、まず共同郵便受けを見るよう勧めた。',
  },
  {
    id: dialogueIds.koyomiD4,
    title: '鍵のない204',
    characterId: characterIds.koyomi,
    day: 4,
    locationId: locationIds.tsukikageHeights,
    priority: 100,
    conditions: { kind: 'day', comparison: 'gte', value: 4 },
    entryNodeId: nodeId(dialogueIds.koyomiD4, 'keys'),
    nodes: [
      line(
        dialogueIds.koyomiD4,
        'keys',
        characterIds.koyomi,
        '鍵束の整理を手伝ってください。札の数と鍵の数が合わないのは、怪異より管理上困ります。',
        'warm',
        'sort',
        [{ kind: 'startSubEvent', subEventId: subEventIds.keySorting }],
      ),
      choice(
        dialogueIds.koyomiD4,
        'sort',
        'narrator',
        '201、202、203の鍵と、鍵のない204の札がある。',
        'neutral',
        [
          option(
            dialogueIds.koyomiD4,
            'accept',
            '刻印を見て三本を部屋札へ戻す',
            'accept',
            'missing',
            [{ kind: 'setFlag', flagId: flagIds.keysGrouped, value: true }],
          ),
          option(
            dialogueIds.koyomiD4,
            'verify',
            '鍵穴の擦れを一つずつ比べる',
            'verify',
            'missing',
            [
              { kind: 'setFlag', flagId: flagIds.keysGrouped, value: true },
              { kind: 'addTrust', characterId: characterIds.koyomi, amount: 1 },
            ],
          ),
          option(
            dialogueIds.koyomiD4,
            'distance',
            'こよみに並べ方を確認してから触る',
            'distance',
            'missing',
            [{ kind: 'setFlag', flagId: flagIds.keysGrouped, value: true }],
          ),
        ],
      ),
      line(
        dialogueIds.koyomiD4,
        'missing',
        characterIds.koyomi,
        '204の札には鍵穴の擦れがありません。部屋が統合された後、札だけ郵便のため残しました。',
        'neutral',
        'small',
        [
          { kind: 'setFlag', flagId: flagIds.key204Missing, value: true },
          { kind: 'discoverClue', clueId: clueIds.oldFloorplan },
        ],
      ),
      line(
        dialogueIds.koyomiD4,
        'small',
        characterIds.koyomi,
        '留め具の小鍵は部屋を開けません。203の郵便受け、その乾いた音の場所へ使います。',
        'warm',
        'end',
        [{ kind: 'setFlag', flagId: flagIds.smallKeyFound, value: true }],
      ),
    ],
    journalSummary: '204に部屋の鍵はなかった。改装で203へ統合され、郵便札だけが残された。',
  },
  {
    id: dialogueIds.koyomiD5Low,
    title: '管理人の引継帳',
    characterId: characterIds.koyomi,
    day: 5,
    locationId: locationIds.tsukikageHeights,
    priority: 63,
    conditions: {
      kind: 'all',
      conditions: [
        { kind: 'day', comparison: 'gte', value: 5 },
        { kind: 'trust', characterId: characterIds.koyomi, comparison: 'lte', value: 2 },
      ],
    },
    entryNodeId: nodeId(dialogueIds.koyomiD5Low, 'ledger'),
    nodes: [
      line(
        dialogueIds.koyomiD5Low,
        'ledger',
        characterIds.koyomi,
        '204の郵便物を保管する決まりは、母からの引継ぎです。昔話より、管理記録を先にどうぞ。',
        'guarded',
        'end',
        [{ kind: 'incrementStat', statId: 'testimoniesHeard', amount: 1 }],
      ),
    ],
    journalSummary: 'こよみは母から204の郵便物保管を引き継いだ。管理人の名も装いも代々同じ。',
  },
  {
    id: dialogueIds.koyomiD5High,
    title: '同じ名を継ぐ人',
    characterId: characterIds.koyomi,
    day: 5,
    locationId: locationIds.tsukikageHeights,
    priority: 90,
    conditions: {
      kind: 'all',
      conditions: [
        { kind: 'day', comparison: 'gte', value: 5 },
        { kind: 'trust', characterId: characterIds.koyomi, comparison: 'gte', value: 3 },
      ],
    },
    entryNodeId: nodeId(dialogueIds.koyomiD5High, 'name'),
    nodes: [
      line(
        dialogueIds.koyomiD5High,
        'name',
        characterIds.koyomi,
        '昔から同じ姿、という噂の答えです。月白こよみは母の名。私も同じ装いで継ぎました。',
        'warm',
        'mail',
        [{ kind: 'incrementStat', statId: 'testimoniesHeard', amount: 1 }],
      ),
      line(
        dialogueIds.koyomiD5High,
        'mail',
        characterIds.koyomi,
        '怪異の噂は便利でした。204の手紙を捨てずに済む。でも、改装の事実まで隠しました。',
        'uneasy',
        'choice',
      ),
      choice(
        dialogueIds.koyomiD5High,
        'choice',
        characterIds.koyomi,
        '名を継ぐことと、役目を継ぐこと。同じだと思いますか。',
        'neutral',
        [
          option(
            dialogueIds.koyomiD5High,
            'accept',
            '説明して受け取るなら、継いでもよい',
            'accept',
            'end',
            [{ kind: 'addTrust', characterId: characterIds.koyomi, amount: 1 }],
          ),
          option(
            dialogueIds.koyomiD5High,
            'verify',
            '名前と役目は分けて記録したい',
            'verify',
            'end',
            [],
          ),
          option(
            dialogueIds.koyomiD5High,
            'distance',
            '継がずに終わらせる自由も必要だ',
            'distance',
            'end',
            [],
          ),
        ],
      ),
    ],
    journalSummary:
      '月白こよみは母娘で同じ名と装いを継ぐ。噂が郵便を守る一方、改装の事実も隠した。',
  },
] as const satisfies readonly Dialogue[]

const minatoDialogues = [
  {
    id: dialogueIds.minatoD3,
    title: '十三番目の呼びかけ',
    characterId: characterIds.minato,
    day: 3,
    locationId: locationIds.yoimachiCafe,
    priority: 110,
    conditions: { kind: 'day', comparison: 'gte', value: 3 },
    entryNodeId: nodeId(dialogueIds.minatoD3, 'voice'),
    nodes: [
      line(
        dialogueIds.minatoD3,
        'voice',
        characterIds.minato,
        '聞こえているなら、返事はしなくていい。ただ、誰かがここにいたことだけ覚えていてほしい。',
        'uneasy',
        'room',
      ),
      line(
        dialogueIds.minatoD3,
        'room',
        characterIds.minato,
        '月影荘二〇四号室の方へ。あなたの転入届を、お預かりしています。',
        'neutral',
        'end',
      ),
    ],
    journalSummary: '湊の声は返事を求めず、204号室の転入届を預かっていると告げた。',
  },
  {
    id: dialogueIds.minatoD4,
    title: '不在と不実在',
    characterId: characterIds.minato,
    day: 4,
    locationId: locationIds.room203,
    priority: 105,
    conditions: { kind: 'letterRead', letterId: letterIds.minatoUnsent },
    entryNodeId: nodeId(dialogueIds.minatoD4, 'letter'),
    nodes: [
      line(
        dialogueIds.minatoD4,
        'letter',
        characterIds.minato,
        '私は町を出る予定がありません。不在と不実在は違います。転出先は空欄のまま返します。',
        'resolute',
        'sumi',
        [{ kind: 'discoverClue', clueId: clueIds.unsentMoveOut }],
      ),
      line(
        dialogueIds.minatoD4,
        'sumi',
        characterIds.minato,
        '澄へ。黙ることを選ばせたら、ごめん。私の名前より、あなたの暮らしを先に守って。',
        'warm',
        'end',
      ),
    ],
    journalSummary: '湊本人は転出を望んでいなかった。澄へ、生活を優先してほしいと書き残した。',
  },
  {
    id: dialogueIds.minatoD7Sparse,
    title: '欠けた最後の録音',
    characterId: characterIds.minato,
    day: 7,
    locationId: locationIds.broadcastHill,
    priority: 80,
    conditions: { kind: 'clueCount', comparison: 'lte', value: 9 },
    entryNodeId: nodeId(dialogueIds.minatoD7Sparse, 'noise'),
    nodes: [
      line(
        dialogueIds.minatoD7Sparse,
        'noise',
        characterIds.minato,
        '雨音で欠けている。……名前を消さないで。仕組みは、誰かが止めるか、受け取って……。',
        'uneasy',
        'choice',
        [{ kind: 'setFlag', flagId: flagIds.finalRecordingHeard, value: true }],
      ),
      choice(
        dialogueIds.minatoD7Sparse,
        'choice',
        'narrator',
        '分からない部分を残したままでも、放送卓は選択を待っている。',
        'resolute',
        [
          option(dialogueIds.minatoD7Sparse, 'return', '町へ名前を返す', 'accept', 'end', [
            { kind: 'setFinalChoice', value: 'return_name' },
            { kind: 'setFlag', flagId: flagIds.finalDecisionMade, value: true },
          ]),
          option(dialogueIds.minatoD7Sparse, 'outside', '記録を外へ持ち出す', 'verify', 'end', [
            { kind: 'setFinalChoice', value: 'take_outside' },
            { kind: 'setFlag', flagId: flagIds.finalDecisionMade, value: true },
          ]),
          option(
            dialogueIds.minatoD7Sparse,
            'inherit',
            '十三番目の役目を引き継ぐ',
            'distance',
            'end',
            [
              { kind: 'setFinalChoice', value: 'inherit_role' },
              { kind: 'setFlag', flagId: flagIds.finalDecisionMade, value: true },
            ],
          ),
        ],
      ),
    ],
    journalSummary: '最後の録音は欠けていた。十分な手掛かりがなくても、選択はできる。',
  },
  {
    id: dialogueIds.minatoD7Full,
    title: '最後の避難者',
    characterId: characterIds.minato,
    day: 7,
    locationId: locationIds.broadcastHill,
    priority: 115,
    conditions: { kind: 'clueCount', comparison: 'gte', value: 10 },
    entryNodeId: nodeId(dialogueIds.minatoD7Full, 'record'),
    nodes: [
      line(
        dialogueIds.minatoD7Full,
        'record',
        characterIds.minato,
        '避難先、十二軒を確認。最後は保守道を使う。これで私の公的な放送は終わりです。',
        'resolute',
        'private',
        [
          { kind: 'discoverClue', clueId: clueIds.evacuationLog },
          { kind: 'setFlag', flagId: flagIds.finalRecordingHeard, value: true },
          { kind: 'setFlag', flagId: flagIds.minatoWishUnderstood, value: true },
        ],
      ),
      line(
        dialogueIds.minatoD7Full,
        'private',
        characterIds.minato,
        '十三番目は私信です。消された名前へ、あなたがいたと届ける。返事を求めないための声です。',
        'warm',
        'system',
      ),
      line(
        dialogueIds.minatoD7Full,
        'system',
        characterIds.minato,
        '台帳と放送を結んだのは私です。放置すれば今いる人まで巻き込む。止め方は三つあります。',
        'uneasy',
        'choice',
      ),
      choice(
        dialogueIds.minatoD7Full,
        'choice',
        'narrator',
        '肯定と代償を理解したうえで、放送卓の一つを選ぶ。',
        'resolute',
        [
          option(dialogueIds.minatoD7Full, 'return', '町へ名前を返す', 'accept', 'end', [
            { kind: 'setFinalChoice', value: 'return_name' },
            { kind: 'setFlag', flagId: flagIds.finalDecisionMade, value: true },
          ]),
          option(dialogueIds.minatoD7Full, 'outside', '記録を外へ持ち出す', 'verify', 'end', [
            { kind: 'setFinalChoice', value: 'take_outside' },
            { kind: 'setFlag', flagId: flagIds.finalDecisionMade, value: true },
          ]),
          option(
            dialogueIds.minatoD7Full,
            'inherit',
            '十三番目の役目を引き継ぐ',
            'distance',
            'end',
            [
              { kind: 'setFinalChoice', value: 'inherit_role' },
              { kind: 'setFlag', flagId: flagIds.finalDecisionMade, value: true },
            ],
          ),
        ],
      ),
    ],
    journalSummary:
      '湊は住民を避難させ、台帳と放送を結んだ。十三番目は忘れられた名への私信だった。',
  },
] as const satisfies readonly Dialogue[]

const tsukiDialogues = [
  {
    id: dialogueIds.tsukiRepeat,
    title: '白と灰色の猫',
    characterId: characterIds.tsuki,
    day: 'repeatable',
    locationId: locationIds.mainStreet,
    priority: 30,
    conditions: { kind: 'day', comparison: 'gte', value: 1 },
    entryNodeId: nodeId(dialogueIds.tsukiRepeat, 'tail'),
    nodes: [
      line(
        dialogueIds.tsukiRepeat,
        'tail',
        'narrator',
        '白と灰色の猫が、こちらを見て一度だけ尻尾を曲げた。首輪の裏に文字がある。',
        'warm',
        'choice',
      ),
      choice(
        dialogueIds.tsukiRepeat,
        'choice',
        'narrator',
        'ツキは逃げず、触れるかどうかをこちらに任せている。',
        'neutral',
        [
          option(dialogueIds.tsukiRepeat, 'pet', 'そっと撫でる', 'accept', 'collar', [
            { kind: 'incrementStat', statId: 'catPetCount', amount: 1 },
            { kind: 'startSubEvent', subEventId: subEventIds.tsukiCollar },
          ]),
          option(dialogueIds.tsukiRepeat, 'watch', '少し離れて見守る', 'distance', 'end', []),
        ],
      ),
      line(
        dialogueIds.tsukiRepeat,
        'collar',
        'narrator',
        '喉を鳴らした拍子に、首輪の「H.M.」が見えた。ツキは丘へ続く路地を振り返る。',
        'warm',
        'end',
        [{ kind: 'setFlag', flagId: flagIds.tsukiCollarRead, value: true }],
      ),
    ],
    journalSummary: 'ツキの首輪にはH.M.の刻印がある。猫は放送塔へ続く古い路地を知っている。',
  },
] as const satisfies readonly Dialogue[]

export const dialogues = [
  ...sumiDialogues,
  ...akariDialogues,
  ...kanadeDialogues,
  ...renDialogues,
  ...koyomiDialogues,
  ...minatoDialogues,
  ...tsukiDialogues,
] as const satisfies readonly Dialogue[]
