import {
  characterIds,
  clueIds,
  endingIds,
  flagIds,
  letterIds,
  locationIds,
  subEventIds,
} from './contentIds'
import type { Letter } from './types'

export const letters = [
  {
    id: letterIds.transferGuide,
    day: 0,
    sender: { kind: 'organization', name: '月影町役場 住民課' },
    recipient: '{{playerName}} 様',
    subject: '転入手続きのご案内',
    paperStyle: 'official',
    bodyBlocks: [
      '月影町へお越しいただき、ありがとうございます。役場の窓口で本状をご提示ください。',
      'お住まいは月影荘203号室です。鍵と住民票は、手続き後にお渡しします。',
      'この町では、書いたお名前を大切に保管します。どうぞ丁寧にお書きください。',
    ],
    arrivalCondition: { kind: 'always' },
    anonymous: false,
    actions: [],
    attachments: [],
    endingVariant: null,
  },
  {
    id: letterIds.to204,
    day: 0,
    sender: { kind: 'unknown', label: '差出人欄は雨でにじんでいる' },
    recipient: '月影荘204号室　星見 湊 様',
    subject: '返事はいりません',
    paperStyle: 'aged',
    bodyBlocks: [
      'あの夜、放送がなければ橋の向こうに残っていました。返事はいりません。',
      'ただ、助かった人がいたことを、あなたのところまで届けたかったのです。',
      '住所がなくなっても、郵便受けだけは覚えていると聞きました。',
    ],
    arrivalCondition: { kind: 'flag', flagId: flagIds.roomKeyReceived, value: true },
    anonymous: true,
    actions: [
      {
        id: 'keep_in_203',
        label: '203号室で預かる',
        condition: { kind: 'letterRead', letterId: letterIds.to204 },
        effects: [{ kind: 'discoverClue', clueId: clueIds.envelope204 }],
        responseBlocks: ['封筒を机の引き出しへしまった。宛先の数字だけが、まだ湿って見える。'],
      },
    ],
    attachments: [clueIds.envelope204],
    endingVariant: null,
  },
  {
    id: letterIds.doNotDiscard,
    day: 1,
    sender: { kind: 'unknown', label: '差出人不明' },
    recipient: '{{playerName}} 様',
    subject: 'この手紙を、まだ捨てないでください',
    paperStyle: 'plain',
    bodyBlocks: [
      'あなたの前に住んでいた人の手紙ではありません。あなたへ届くのを待っていました。',
      '十二まで読み終えても、紙を数え直してください。空いた場所も一枚として。',
      '声が名前を呼んでも、返事はいりません。覚えることと、答えることは別です。',
    ],
    arrivalCondition: { kind: 'day', comparison: 'gte', value: 1 },
    anonymous: true,
    actions: [
      {
        id: 'keep_letter',
        label: '手紙を残す',
        condition: { kind: 'letterRead', letterId: letterIds.to204 },
        effects: [{ kind: 'setFlag', flagId: flagIds.allAnonymousLettersRead, value: true }],
        responseBlocks: ['日記へ挟む。紙は薄いのに、閉じたページが少し持ち上がった。'],
      },
      {
        id: 'leave_on_desk',
        label: '机に置いて距離を取る',
        condition: { kind: 'letterRead', letterId: letterIds.to204 },
        effects: [{ kind: 'setFlag', flagId: flagIds.allAnonymousLettersRead, value: true }],
        responseBlocks: ['捨てずに机へ置いた。窓を閉めると、紙の音も止んだ。'],
      },
    ],
    attachments: [],
    endingVariant: null,
  },
  {
    id: letterIds.historyReturn,
    day: 2,
    sender: { kind: 'character', characterId: characterIds.akari },
    recipient: '{{playerName}} さん',
    subject: '町史を返すときのお願い',
    paperStyle: 'aged',
    bodyBlocks: [
      '貸した町史は、欠けているところも本の一部です。無理に別の紙で埋めないでください。',
      '挟まっている三枚の紙片を見つけたら、本と一緒に持ってきてください。',
      '読めない行があれば、そのままで。消えた字を急いで決める必要はありません。',
    ],
    arrivalCondition: { kind: 'locationVisited', locationId: locationIds.toukaBooks },
    anonymous: false,
    actions: [
      {
        id: 'accept_repair',
        label: '紙片を探す',
        condition: { kind: 'always' },
        effects: [{ kind: 'startSubEvent', subEventId: subEventIds.tornHistory }],
        responseBlocks: ['紙片の形を日記に写した。三枚とも、端に同じ水染みがあるらしい。'],
      },
    ],
    attachments: [clueIds.missingPage13],
    endingVariant: null,
  },
  {
    id: letterIds.cafeInvitation,
    day: 3,
    sender: { kind: 'character', characterId: characterIds.kanade },
    recipient: '{{playerName}}さん',
    subject: '閉店後、少しだけ',
    paperStyle: 'notebook',
    bodyBlocks: [
      '古いカセットが見つかりました。ラベルは空白だけど、雨の日の放送が入っています。',
      '今夜、宵待で再生します。怖いものじゃなく、聞き落とされた声だと思いたいです。',
      '十一時十三分より前に来てください。クリームソーダは、溶けないうちに出します。',
    ],
    arrivalCondition: { kind: 'day', comparison: 'gte', value: 3 },
    anonymous: false,
    actions: [
      {
        id: 'accept_invitation',
        label: '宵待へ行く',
        condition: { kind: 'always' },
        effects: [{ kind: 'startSubEvent', subEventId: subEventIds.cafeCassette }],
        responseBlocks: ['時刻を日記へ書いた。窓の外で、遠い試験音が十二回鳴った。'],
      },
    ],
    attachments: [],
    endingVariant: null,
  },
  {
    id: letterIds.sumiMeeting,
    day: 5,
    sender: { kind: 'character', characterId: characterIds.sumi },
    recipient: '{{playerName}} 様',
    subject: '閉庁後の住民課について',
    paperStyle: 'blue-ink',
    bodyBlocks: [
      '窓口ではお話しできなかったことがあります。閉庁後、住民課へお越しください。',
      '兄の名前を消した書類と、消せなかった写真をお見せします。',
      '正しさを決めてほしいのではありません。私が黙った理由も、一緒に聞いてください。',
    ],
    arrivalCondition: {
      kind: 'all',
      conditions: [
        { kind: 'day', comparison: 'gte', value: 5 },
        { kind: 'clueCount', comparison: 'gte', value: 6 },
      ],
    },
    anonymous: false,
    actions: [
      {
        id: 'accept_meeting',
        label: '閉庁後に会う',
        condition: { kind: 'always' },
        effects: [{ kind: 'addTrust', characterId: characterIds.sumi, amount: 1 }],
        responseBlocks: ['青いインクの時刻を日記へ写した。文字の終わりだけ、筆圧が弱い。'],
      },
    ],
    attachments: [clueIds.sumiPhoto],
    endingVariant: null,
  },
  {
    id: letterIds.minatoUnsent,
    day: 4,
    sender: { kind: 'character', characterId: characterIds.minato },
    recipient: '月影町役場 住民課 御中',
    subject: '転出届を出さない理由',
    paperStyle: 'aged',
    bodyBlocks: [
      '私は町を出る予定がありません。この用紙は、空欄のまま返します。',
      '放送の十三番目は私的な連絡です。公報にできない名前を、誰か一人へ届けます。',
      'もし私が戻らなくても、転出と書かないでください。不在と不実在は違います。',
      '澄へ。黙ることを選ばせてしまったら、ごめん。あなたの暮らしを先に守ってください。',
    ],
    arrivalCondition: { kind: 'flag', flagId: flagIds.doubleBottomOpened, value: true },
    anonymous: false,
    actions: [
      {
        id: 'record_unsent_form',
        label: '未送信の転出届を記録する',
        condition: { kind: 'always' },
        effects: [{ kind: 'discoverClue', clueId: clueIds.unsentMoveOut }],
        responseBlocks: ['署名欄は埋まっている。転出先と日付だけが、最後まで空白だった。'],
      },
    ],
    attachments: [clueIds.unsentMoveOut, clueIds.mailboxFalseBottom],
    endingVariant: null,
  },
  {
    id: letterIds.renSafetyNote,
    day: 5,
    sender: { kind: 'character', characterId: characterIds.ren },
    recipient: '{{playerName}}さん',
    subject: '放送塔へ行く前に',
    paperStyle: 'official',
    bodyBlocks: [
      '柵を越えるなら、私に声をかけてください。無断侵入の話ではなく、斜面の安全の話です。',
      '父の日誌を同封します。記録を書き換えた理由も、結果も、どちらも残すべきだと思います。',
      '真実を追うのは止めません。ただ、帰る場所まで見失わないでください。',
    ],
    arrivalCondition: {
      kind: 'all',
      conditions: [
        { kind: 'day', comparison: 'gte', value: 5 },
        { kind: 'trust', characterId: characterIds.ren, comparison: 'gte', value: 2 },
      ],
    },
    anonymous: false,
    actions: [
      {
        id: 'read_log',
        label: '父の業務日誌を読む',
        condition: { kind: 'always' },
        effects: [{ kind: 'discoverClue', clueId: clueIds.renFatherLog }],
        responseBlocks: ['日誌には避難誘導の成功と、翌日の訂正命令が同じ筆圧で書かれている。'],
      },
    ],
    attachments: [clueIds.renFatherLog],
    endingVariant: null,
  },
  {
    id: letterIds.endingA,
    day: 7,
    sender: { kind: 'character', characterId: characterIds.sumi },
    recipient: '{{playerName}} 様',
    subject: 'ようこそ、月影町へ',
    paperStyle: 'blue-ink',
    bodyBlocks: [
      '兄の名前が台帳へ戻りました。空欄だった住所には、旧204区画と記してあります。',
      '町は一度に正しくなりません。それでも、消さずに直す方法を覚え始めました。',
      '{{playerName}}様の住民票にも、記録係補佐と追記しました。今後とも、よろしくお願いします。',
    ],
    arrivalCondition: { kind: 'endingReached', endingId: endingIds.a },
    anonymous: false,
    actions: [],
    attachments: [],
    endingVariant: endingIds.a,
  },
  {
    id: letterIds.endingB,
    day: 7,
    sender: { kind: 'unknown', label: '車内の回覧板' },
    recipient: '{{playerName}} 様',
    subject: '終点の向こうで読む方へ',
    paperStyle: 'plain',
    bodyBlocks: [
      '複製した町史と録音は、町の外でも同じ重さです。誰に渡すかは急がないでください。',
      '窓の外で人口表示が一つ減りました。それは喪失か、数え直しの始まりかもしれません。',
      'この紙は十三枚目です。町を離れても、読んだ名前まで置いていく必要はありません。',
    ],
    arrivalCondition: { kind: 'endingReached', endingId: endingIds.b },
    anonymous: true,
    actions: [],
    attachments: [],
    endingVariant: endingIds.b,
  },
  {
    id: letterIds.endingC,
    day: 7,
    sender: { kind: 'character', characterId: characterIds.minato },
    recipient: '十三番目の配達人 {{playerName}} 様',
    subject: '最初の配達先',
    paperStyle: 'aged',
    bodyBlocks: [
      '次に届ける名前は、町史の余白にあります。声に出さず、本人へ手紙を渡してください。',
      '放送は月に一度、短い私信だけにしてください。返事を求めないことも忘れずに。',
      '役目は鎖ではありません。重くなったら、別の誰かへ説明して渡してください。',
    ],
    arrivalCondition: { kind: 'endingReached', endingId: endingIds.c },
    anonymous: false,
    actions: [],
    attachments: [],
    endingVariant: endingIds.c,
  },
  {
    id: letterIds.endingD,
    day: 7,
    sender: { kind: 'unknown', label: '消印のない封筒' },
    recipient: '宛名の薄れた住民票の持ち主へ',
    subject: 'まだ読まれていない紙',
    paperStyle: 'plain',
    bodyBlocks: [
      '町を離れる選択も、間違いではありません。知らない重さを持てない夜はあります。',
      'あなたの名前は薄れましたが、消えてはいません。最終日前の机に記録を残しました。',
      'もう一度読むなら、十二枚の外ではなく、空いた場所から始めてください。',
    ],
    arrivalCondition: { kind: 'endingReached', endingId: endingIds.d },
    anonymous: true,
    actions: [],
    attachments: [],
    endingVariant: endingIds.d,
  },
] as const satisfies readonly Letter[]

export const endingLetters = letters.filter((letter) => letter.endingVariant !== null)
