import { clueIds, flagIds, locationIds } from './contentIds'
import type { Location } from './types'

export const locations = [
  {
    id: locationIds.station,
    name: '月影町駅',
    shortName: '駅',
    kind: 'outdoor',
    description: '一本の線路が夕闇へ消える、小さな終着駅。時計だけが妙に新しい。',
    atmosphere: '去った列車の鉄音と、濡れた枕木の匂いが残る。',
    landmarks: ['終点標', '11時13分を指す時計', '古い木のベンチ'],
    mapPosition: { x: -8, z: 5 },
    availableFromDay: 0,
    accessCondition: { kind: 'always' },
    unlockHint: '物語の到着地点です。',
  },
  {
    id: locationIds.townHall,
    name: '月影町役場',
    shortName: '役場',
    kind: 'indoor',
    description: '青いインクの匂いがする木造庁舎。人口表示は入口脇にある。',
    atmosphere: '紙をめくる音が、時計の秒針より少し遅れて響く。',
    landmarks: ['住民課窓口', '人口表示板', '古い住民台帳'],
    mapPosition: { x: -2, z: 1 },
    availableFromDay: 0,
    accessCondition: { kind: 'always' },
    unlockHint: '駅前の坂を下り、青い庇の建物へ。',
  },
  {
    id: locationIds.mainStreet,
    name: '月影通り',
    shortName: '通り',
    kind: 'outdoor',
    description: '商店と月影荘を結ぶ短い通り。夕方になると琥珀色の灯がともる。',
    atmosphere: '雨上がりの舗道に、窓明かりと空の群青が重なる。',
    landmarks: ['時計店の看板', '琥珀色の街灯', '小さな路地'],
    mapPosition: { x: 0, z: 0 },
    availableFromDay: 0,
    accessCondition: { kind: 'always' },
    unlockHint: '町の中央を通る道です。',
  },
  {
    id: locationIds.bulletinBoard,
    name: '町内掲示板',
    shortName: '掲示板',
    kind: 'threshold',
    description: '木枠の中に十二枚の紙が並ぶ。右下には一枚ぶんの紙跡がある。',
    atmosphere: '風が吹くたび、画鋲に留められた紙が小さく息をする。',
    landmarks: ['十二枚の掲示', '古い画鋲穴', '不自然な右下の隙間'],
    mapPosition: { x: 2, z: 0 },
    availableFromDay: 1,
    accessCondition: { kind: 'day', comparison: 'gte', value: 1 },
    unlockHint: '役場と月影通りの間にあります。',
  },
  {
    id: locationIds.toukaBooks,
    name: '古書店「灯下書房」',
    shortName: '灯下書房',
    kind: 'indoor',
    description: '町史と古地図が天井近くまで積まれた店。奥で琥珀色のランプが光る。',
    atmosphere: '乾いた紙と木の匂い。ページを閉じても文章の気配が残る。',
    landmarks: ['郷土資料棚', '琥珀色のランプ', '紙片を挟んだ古地図'],
    mapPosition: { x: 3, z: -2 },
    availableFromDay: 1,
    accessCondition: { kind: 'day', comparison: 'gte', value: 1 },
    unlockHint: '月影通りの橙色の看板を探してください。',
  },
  {
    id: locationIds.yoimachiCafe,
    name: '喫茶「宵待」',
    shortName: '宵待',
    kind: 'indoor',
    description: '古いラジオと青いクリームソーダが似合う喫茶店。夜も窓が明るい。',
    atmosphere: '氷の鳴る音の奥で、使われていないラジオがかすかに唸る。',
    landmarks: ['古いラジオ', 'カセットデッキ', '窓際の丸卓'],
    mapPosition: { x: -1, z: -3 },
    availableFromDay: 1,
    accessCondition: { kind: 'day', comparison: 'gte', value: 1 },
    unlockHint: '月影通りの青緑色の庇が目印です。',
  },
  {
    id: locationIds.tsukikageHeights,
    name: '月影荘',
    shortName: '月影荘',
    kind: 'indoor',
    description: '古い二階建ての共同住宅。廊下の壁紙は一箇所だけ模様がずれる。',
    atmosphere: '住人の夕食の匂いと、数の合わない郵便受けが生活の中に並ぶ。',
    landmarks: ['共同郵便受け', '203号室の扉', '継ぎ目のある廊下'],
    mapPosition: { x: 4, z: 3 },
    availableFromDay: 0,
    accessCondition: { kind: 'flag', flagId: flagIds.roomKeyReceived, value: true },
    unlockHint: '役場で203号室の鍵を受け取ってください。',
  },
  {
    id: locationIds.room203,
    name: '自室203号室',
    shortName: '自室',
    kind: 'indoor',
    description: 'まだ箱の少ない部屋。壁の奥に、もう一部屋ぶんの静けさがある。',
    atmosphere: '窓から放送塔が見える。机の上なら手紙と記録を落ち着いて読める。',
    landmarks: ['手紙を読む机', '放送塔の見える窓', '幅の広すぎる東壁'],
    mapPosition: { x: 4.4, z: 3.2 },
    availableFromDay: 0,
    accessCondition: { kind: 'flag', flagId: flagIds.roomKeyReceived, value: true },
    unlockHint: '月影荘の二階、白い札の203号室です。',
  },
  {
    id: locationIds.broadcastHill,
    name: '放送塔の丘',
    shortName: '放送塔',
    kind: 'outdoor',
    description: '町を見下ろす低い丘。錆びた塔の赤色灯が十三秒ごとにまたたく。',
    atmosphere: '風の間に、遠いマイクの息づかいのようなノイズが混ざる。',
    landmarks: ['放送塔', '立入禁止柵', '旧い保守道'],
    mapPosition: { x: 8, z: -6 },
    availableFromDay: 6,
    accessCondition: { kind: 'clue', clueId: clueIds.thirteenthNotice },
    unlockHint: '十三番目の回覧板を読み、丘への道を確かめてください。',
  },
] as const satisfies readonly Location[]
